export interface DemoEntry {
  /** Sleutel van het demobestand in /demos. */
  key: string;
  title: string;
  description?: string;
  /** Inhoud links uitlijnen in plaats van centreren. */
  align?: "center" | "start" | "block";
  /** Toont een "nieuw"-label bij deze demo. */
  isNew?: boolean;
  /** Toont een "bijgewerkt"-label bij deze demo. Wordt genegeerd als isNew aanstaat. */
  isUpdated?: boolean;
}

export interface ComponentEntry {
  slug: string;
  name: string;
  description: string;
  category: string;
  /** Bestanden uit packages/ui die dit component nodig heeft. */
  files: string[];
  /** Andere componenten die mee gekopieerd worden. */
  dependsOn?: string[];
  /** npm-packages die dit component nodig heeft. Alleen de motion-laag gebruikt dit. */
  requires?: string[];
  demos: DemoEntry[];
  /** Namen van interfaces waarvan de props-tabel getoond wordt. */
  props?: string[];
  notes?: string[];
  /** Toont een "nieuw"-label in de navigatie en op de pagina. */
  isNew?: boolean;
  /** Toont een "bijgewerkt"-label in de navigatie en op de pagina. Wordt genegeerd als isNew aanstaat. */
  isUpdated?: boolean;
}

export const CATEGORIES = [
  "Basis",
  "Formulieren",
  "Overlays",
  "Navigatie",
  "Datum & planning",
  "Data",
  "Feedback",
  "Layout",
  "Motion",
] as const;

/*
 * Labels per release: bij elke release gaan ALLE isNew- en isUpdated-vlaggen eruit,
 * en krijgen alleen de componenten van díé release er weer een. Zo staat er nooit
 * "nieuw" op iets van drie releases geleden.
 *
 * Elke stap van de opbouw voegt hier componenten toe.
 * Houd de opmaak aan (twee spaties + "{" op een eigen regel): scripts/build-registry.mjs leest dit bestand.
 */
export const COMPONENTS: ComponentEntry[] = [
  {
    slug: "button",
    name: "Button",
    description: "Knop met zes varianten, drie maten, iconen en laadstatus.",
    category: "Basis",
    files: ["button.tsx", "button.css"],
    dependsOn: ["spinner"],
    demos: [
      { key: "button-variants", title: "Varianten" },
      { key: "button-sizes", title: "Maten en iconen" },
      { key: "button-states", title: "Laden, uitgeschakeld en groep" },
    ],
    props: ["ButtonProps"],
    notes: [
      "Met asChild rendert de knop jouw eigen element — bijvoorbeeld een link of next/link — met behoud van alle stijl en states.",
    ],
  },
  {
    slug: "badge",
    name: "Badge",
    description: "Compact label voor status, categorie of telling.",
    category: "Basis",
    files: ["badge.tsx", "badge.css"],
    demos: [
      { key: "badge-tones", title: "Tonen" },
      { key: "badge-usage", title: "Met stip en icoon" },
    ],
    props: ["BadgeProps"],
  },
  {
    slug: "card",
    name: "Card",
    description: "Basiscontainer met kop, inhoud en voettekst.",
    category: "Basis",
    files: ["card.tsx", "card.css"],
    demos: [{ key: "card-basic", title: "Opbouw", align: "block" }],
    props: ["CardProps"],
  },
  {
    slug: "spinner",
    name: "Spinner",
    description: "Ronddraaiende laadindicator die de tekstkleur erft.",
    category: "Basis",
    files: ["spinner.tsx", "spinner.css"],
    demos: [{ key: "spinner-basic", title: "Maten" }],
    props: ["SpinnerProps"],
  },
  {
    slug: "icon",
    name: "Icon",
    description: "Eigen icon set: één stroke-based glyph per naam.",
    category: "Basis",
    files: ["../icons/icon.tsx", "../icons/icons.ts"],
    demos: [{ key: "icon-gallery", title: "Volledige set", align: "block" }],
    props: ["IconProps"],
  },
  {
    slug: "separator",
    name: "Separator",
    description: "Scheidingslijn, horizontaal of verticaal, met optioneel label.",
    category: "Basis",
    files: ["separator.tsx", "separator.css"],
    demos: [{ key: "separator-basic", title: "Varianten", align: "block" }],
    props: ["SeparatorProps"],
  },
  {
    slug: "kbd",
    name: "Kbd",
    description: "Toetsaanslag of sneltoets tonen.",
    category: "Basis",
    files: ["kbd.tsx", "kbd.css"],
    demos: [{ key: "kbd-basic", title: "Sneltoetsen" }],
    props: ["KbdProps"],
  },
  {
    slug: "skeleton",
    name: "Skeleton",
    description: "Laadplaceholder met shimmer.",
    category: "Basis",
    files: ["skeleton.tsx", "skeleton.css"],
    demos: [{ key: "skeleton-basic", title: "Vormen", align: "block" }],
    props: ["SkeletonProps"],
  },
  {
    slug: "avatar",
    name: "Avatar",
    description: "Foto of initialen, met statusstip en groepsweergave.",
    category: "Basis",
    files: ["avatar.tsx", "avatar.css"],
    demos: [{ key: "avatar-basic", title: "Maten, status en groep" }],
    props: ["AvatarProps", "AvatarGroupProps"],
    notes: ["Met initials zet je zelf de letters, bijvoorbeeld een trigram van drie tekens in plaats van de afgeleide initialen."],
    isUpdated: true,
  },
  {
    slug: "chip",
    name: "Chip",
    description: "Klikbaar filterlabel, of een verwijderbare tag.",
    category: "Basis",
    files: ["chip.tsx", "chip.css"],
    demos: [{ key: "chip-basic", title: "Filters en tags", align: "block" }],
    props: ["ChipProps", "ChipGroupProps"],
    notes: ["Badge is een label om te lezen, Chip is er een om op te klikken. Met onRemove wordt het een tag met kruisje."],
  },
  {
    slug: "copy-button",
    name: "CopyButton",
    description: "Kopieert een waarde en bevestigt dat kort met een vinkje.",
    category: "Basis",
    files: ["copy-button.tsx", "copy-button.css"],
    demos: [{ key: "copybutton-basic", title: "Kopiëren", align: "block" }],
    props: ["CopyButtonProps"],
  },
  {
    slug: "label",
    name: "Label",
    description: "Bijschrift voor een formulierveld, met verplicht-markering.",
    category: "Formulieren",
    files: ["label.tsx", "label.css"],
    demos: [{ key: "label-basic", title: "Standaard", align: "block" }],
    props: ["LabelProps"],
  },
  {
    slug: "input",
    name: "Input",
    description: "Tekstveld met iconen, addon, maten en foutstatus.",
    category: "Formulieren",
    files: ["input.tsx", "input.css"],
    dependsOn: ["field"],
    demos: [
      { key: "input-basic", title: "Maten en varianten", align: "block" },
      { key: "input-affix", title: "Icoon, suffix en addon", align: "block" },
    ],
    props: ["InputProps"],
  },
  {
    slug: "textarea",
    name: "Textarea",
    description: "Meerregelig tekstveld, optioneel meegroeiend.",
    category: "Formulieren",
    files: ["textarea.tsx", "textarea.css"],
    dependsOn: ["field"],
    demos: [{ key: "textarea-basic", title: "Standaard en meegroeiend", align: "block" }],
    props: ["TextareaProps"],
  },
  {
    slug: "field",
    name: "Field",
    description: "Koppelt label, hint en foutmelding aan één invoerveld.",
    category: "Formulieren",
    files: ["field.tsx", "field.css"],
    dependsOn: ["label"],
    demos: [{ key: "field-basic", title: "Label, hint en fout", align: "block" }],
    props: ["FieldProps"],
    notes: [
      "Field zet automatisch id, aria-describedby en aria-invalid op het veld erin — je hoeft niets handmatig te koppelen.",
    ],
  },
  {
    slug: "fieldset",
    name: "Fieldset",
    description: "Groepje bij elkaar horende velden met een gedeelde titel.",
    category: "Formulieren",
    files: ["fieldset.tsx", "fieldset.css"],
    demos: [{ key: "fieldset-basic", title: "Contactgegevens", description: "Met kader, uitleg en een rij velden naast elkaar.", align: "block" }],
    props: ["FieldsetProps"],
    notes: [
      "Gebruikt het echte fieldset-element, dus disabled zet in één keer alles erin uit — ook velden van derden.",
      "Met row staan de velden naast elkaar; ze vouwen vanzelf om op smalle schermen.",
    ],
  },
  {
    slug: "checkbox",
    name: "Checkbox",
    description: "Aanvinkvakje met derde staat en beschrijving.",
    category: "Formulieren",
    files: ["checkbox.tsx", "checkbox.css"],
    demos: [{ key: "checkbox-basic", title: "Staten", align: "block" }],
    props: ["CheckboxProps"],
  },
  {
    slug: "radio-group",
    name: "RadioGroup",
    description: "Groep keuzerondjes, ook als klikbare kaarten.",
    category: "Formulieren",
    files: ["radio-group.tsx", "radio-group.css"],
    demos: [
      { key: "radio-basic", title: "Standaard", align: "block" },
      { key: "radio-cards", title: "Als kaarten", align: "block" },
    ],
    props: ["RadioGroupProps", "RadioProps"],
  },
  {
    slug: "rating",
    name: "Rating",
    description: "Sterren om iets te beoordelen of een score te tonen.",
    category: "Formulieren",
    files: ["rating.tsx", "rating.css"],
    demos: [{ key: "rating-basic", title: "Kiezen en tonen", description: "Halve sterren, alleen-lezen variant en bediening met het toetsenbord." }],
    props: ["RatingProps"],
    notes: [
      "Met half klik je op de linkerhelft van een ster voor een halve punt.",
      "readOnly maakt er een weergave van: de rol wordt img in plaats van slider.",
    ],
  },
  {
    slug: "switch",
    name: "Switch",
    description: "Aan/uit-schakelaar met label en beschrijving.",
    category: "Formulieren",
    files: ["switch.tsx", "switch.css"],
    demos: [{ key: "switch-basic", title: "Varianten", align: "block" }],
    props: ["SwitchProps"],
  },
  {
    slug: "toggle",
    name: "Toggle",
    description: "Knop die ingedrukt blijft staan, los of in een groep.",
    category: "Formulieren",
    files: ["toggle.tsx", "toggle.css"],
    demos: [{ key: "toggle-basic", title: "Los, meervoudig en enkelvoudig", description: "Toggle, ToggleGroup met type multiple, en een aaneengesloten groep." }],
    props: ["ToggleProps", "ToggleGroupProps", "ToggleGroupItemProps"],
    notes: [
      "Voor een aan/uit-instelling gebruik je Switch; Toggle is voor een knop die ingedrukt blijft, zoals vet in een werkbalk.",
      "ToggleGroup met type single lijkt op Segmented, maar hier mag ook niets gekozen zijn.",
    ],
  },
  {
    slug: "select",
    name: "Select",
    description: "Eigen keuzelijst — geen native select, volledig stijlbaar.",
    category: "Formulieren",
    files: ["select.tsx", "select.css"],
    demos: [
      { key: "select-basic", title: "Standaard", align: "block" },
      { key: "select-rich", title: "Met groepen, iconen en zoeken", align: "block" },
    ],
    props: ["SelectProps", "SelectItemProps", "SelectContentProps"],
  },
  {
    slug: "alert",
    name: "Alert",
    description: "Inline melding met toon, titel en actie.",
    category: "Feedback",
    files: ["alert.tsx", "alert.css"],
    demos: [{ key: "alert-basic", title: "Tonen", align: "block" }],
    props: ["AlertProps"],
  },
  {
    slug: "empty-state",
    name: "EmptyState",
    description: "Lege lijst, geen resultaten of nog niets ingesteld.",
    category: "Feedback",
    files: ["empty-state.tsx", "empty-state.css"],
    demos: [{ key: "empty-basic", title: "Standaard", align: "block" }],
    props: ["EmptyStateProps"],
  },
  {
    slug: "indicator",
    name: "Indicator",
    description: "Telbadge of stip op de hoek van een knop, avatar of tab.",
    category: "Feedback",
    files: ["indicator.tsx", "indicator.css"],
    demos: [{ key: "indicator-basic", title: "Tellers en stippen", description: "Met max voor 99+, een stip, en verborgen bij nul." }],
    props: ["IndicatorProps"],
    notes: [
      "Zonder label is het hoekje aria-hidden: het getal hoort dan ook in de knoptekst te staan, anders hoort een schermlezer het niet.",
      "hidden laat het element staan maar toont niets — handig bij nul meldingen.",
    ],
  },
  {
    slug: "progress",
    name: "Progress",
    description: "Voortgangsbalk en ronde variant, ook onbepaald.",
    category: "Data",
    files: ["progress.tsx", "progress.css"],
    demos: [{ key: "progress-basic", title: "Balk en cirkel", align: "block" }],
    props: ["ProgressProps", "ProgressCircleProps"],
  },
  {
    slug: "tabs",
    name: "Tabs",
    description: "Tabbladen in drie stijlen, met pijltjesnavigatie.",
    category: "Navigatie",
    files: ["tabs.tsx", "tabs.css"],
    demos: [
      { key: "tabs-basic", title: "Line, pill en solid", align: "block" },
    ],
    props: ["TabsProps", "TabsTriggerProps"],
  },
  {
    slug: "segmented",
    name: "Segmented",
    description: "Compacte keuzeschakelaar voor weergaven en filters.",
    category: "Navigatie",
    files: ["segmented.tsx", "segmented.css"],
    demos: [{ key: "segmented-basic", title: "Varianten", align: "block" }],
    props: ["SegmentedProps", "SegmentedOption"],
  },
  {
    slug: "accordion",
    name: "Accordion",
    description: "In- en uitklapbare secties, enkel of meervoudig.",
    category: "Navigatie",
    files: ["accordion.tsx", "accordion.css"],
    demos: [{ key: "accordion-basic", title: "Varianten", align: "block" }],
    props: ["AccordionProps", "AccordionItemProps"],
  },
  {
    slug: "collapsible",
    name: "Collapsible",
    description: "Eén stuk inhoud dat open- en dichtklapt, met echte hoogte-animatie.",
    category: "Navigatie",
    files: ["collapsible.tsx", "collapsible.css"],
    demos: [{ key: "collapsible-basic", title: "Eerdere afspraken", description: "De hoogte groeit mee met de inhoud, zonder die te meten.", align: "block" }],
    props: ["CollapsibleProps", "CollapsibleTriggerProps", "CollapsibleContentProps"],
    notes: [
      "Gebruik Accordion als er meerdere secties zijn die elkaar afwisselen; Collapsible is voor één blok.",
      "De animatie werkt met grid-template-rows van 0fr naar 1fr, dus ook inhoud die onderweg verandert schuift netjes mee.",
    ],
  },
  {
    slug: "menubar",
    name: "Menubar",
    description: "Vaste menubalk zoals in een desktop-app: Dossier, Bewerken, Beeld.",
    category: "Navigatie",
    files: ["menubar.tsx", "menubar.css"],
    dependsOn: ["dropdown-menu"],
    demos: [{ key: "menubar-basic", title: "Drie menu's", description: "Eenmaal open volgen de andere menu's je muis, zoals in een echte menubalk." }],
    props: ["MenubarProps", "MenubarMenuProps", "MenubarTriggerProps"],
    notes: [
      "Gebruikt dezelfde items als DropdownMenu: DropdownMenuItem, -Label, -Separator en -Group werken hierbinnen.",
      "Bedoeld voor schermen met een muis; op mobiel is een DropdownMenu of Drawer een betere keuze.",
    ],
  },
  {
    slug: "breadcrumb",
    name: "Breadcrumb",
    description: "Kruimelpad met scheidingstekens.",
    category: "Navigatie",
    files: ["breadcrumb.tsx", "breadcrumb.css"],
    demos: [{ key: "breadcrumb-basic", title: "Standaard", align: "block" }],
    props: ["BreadcrumbProps", "BreadcrumbItemProps"],
  },
  {
    slug: "pagination",
    name: "Pagination",
    description: "Paginanavigatie met ellipsis en samenvatting.",
    category: "Navigatie",
    files: ["pagination.tsx", "pagination.css"],
    demos: [{ key: "pagination-basic", title: "Standaard", align: "block" }],
    props: ["PaginationProps"],
  },
  {
    slug: "stepper",
    name: "Stepper",
    description: "Voortgang door een meerstapsflow.",
    category: "Navigatie",
    files: ["stepper.tsx", "stepper.css"],
    demos: [{ key: "stepper-basic", title: "Horizontaal en verticaal", align: "block" }],
    props: ["StepperProps"],
  },
  {
    slug: "table",
    name: "Table",
    description: "Datatabel met sorteerbare koppen, dichte modus en toolbar.",
    category: "Data",
    files: ["table.tsx", "table.css"],
    demos: [{ key: "table-basic", title: "Sorteerbare tabel", align: "block" }],
    props: ["TableProps", "TableHeadProps", "TableRowProps"],
    notes: [
      "striped geeft om de andere rij een lichte achtergrond; stickyHeader laat de kop staan zodra je maxHeight meegeeft.",
      "Een selectiekolom maak je met een gewone Checkbox in de eerste cel — zo blijft de logica bij jou.",
    ],
    isUpdated: true,
  },
  {
    slug: "dialog",
    name: "Dialog",
    description: "Modaal venster met focus-trap, Escape en overlay.",
    category: "Overlays",
    files: ["dialog.tsx", "dialog.css"],
    dependsOn: ["button"],
    demos: [
      { key: "dialog-basic", title: "Standaard" },
      { key: "dialog-form", title: "Met formulier" },
    ],
    props: ["DialogProps", "DialogContentProps"],
  },
  {
    slug: "alert-dialog",
    name: "AlertDialog",
    description: "Bevestiging voor een actie die je niet zomaar terugdraait.",
    category: "Overlays",
    files: ["alert-dialog.tsx", "alert-dialog.css"],
    dependsOn: ["dialog", "button"],
    demos: [{ key: "alertdialog-basic", title: "Verwijderen bevestigen", description: "Twee manieren: de dialoog zelf plaatsen, of useConfirm() als belofte." }],
    props: ["AlertDialogProps"],
    notes: [
      "Anders dan Dialog: geen kruisje, klikken naast de dialoog sluit niet en de focus staat op Annuleren.",
      "Geeft onConfirm een belofte terug, dan blijft de knop laden tot ze klaar is en sluit de dialoog daarna.",
      "useConfirm() heeft een ConfirmProvider bovenaan je app nodig.",
    ],
  },
  {
    slug: "drawer",
    name: "Drawer",
    description: "Paneel dat vanaf een zijkant inschuift.",
    category: "Overlays",
    files: ["drawer.tsx", "drawer.css"],
    dependsOn: ["dialog", "button"],
    demos: [{ key: "drawer-basic", title: "Vier richtingen" }],
    props: ["DrawerProps", "DrawerContentProps"],
  },
  {
    slug: "popover",
    name: "Popover",
    description: "Zwevend paneel dat automatisch flipt bij weinig ruimte.",
    category: "Overlays",
    files: ["popover.tsx", "popover.css"],
    demos: [{ key: "popover-basic", title: "Standaard" }],
    props: ["PopoverProps", "PopoverContentProps"],
  },
  {
    slug: "hover-card",
    name: "HoverCard",
    description: "Kaartje met extra context bij hoveren, groter dan een tooltip.",
    category: "Overlays",
    files: ["hover-card.tsx", "hover-card.css"],
    demos: [{ key: "hovercard-basic", title: "Patiënt in een zin", description: "Hover over de naam; de kaart blijft open terwijl je ernaartoe beweegt." }],
    props: ["HoverCardProps", "HoverCardContentProps"],
    notes: [
      "Alleen voor aanvullende informatie: op touch bestaat hoveren niet, en de kaart opent daar dus nooit.",
      "Toetsenbordgebruikers krijgen de kaart bij focus op de trigger.",
    ],
  },
  {
    slug: "tooltip",
    name: "Tooltip",
    description: "Korte uitleg bij hover én toetsenbordfocus.",
    category: "Overlays",
    files: ["tooltip.tsx", "tooltip.css"],
    demos: [{ key: "tooltip-basic", title: "Vier zijden" }],
    props: ["TooltipProps"],
  },
  {
    slug: "dropdown-menu",
    name: "DropdownMenu",
    description: "Actiemenu met pijltjesnavigatie, sneltoetsen en secties.",
    category: "Overlays",
    files: ["dropdown-menu.tsx", "dropdown-menu.css"],
    dependsOn: ["button"],
    demos: [{ key: "dropdown-basic", title: "Menu met secties" }],
    props: ["DropdownMenuProps", "DropdownMenuItemProps"],
  },
  {
    slug: "context-menu",
    name: "ContextMenu",
    description: "Menu op de rechtermuisknop, op de plek van de cursor.",
    category: "Overlays",
    files: ["context-menu.tsx", "context-menu.css"],
    dependsOn: ["dropdown-menu"],
    demos: [{ key: "contextmenu-basic", title: "Rechtermuisklik", description: "Dezelfde items als DropdownMenu, inclusief toetsenbordnavigatie." }],
    props: ["ContextMenuProps", "ContextMenuTriggerProps"],
    notes: [
      "Gebruikt dezelfde items als DropdownMenu: DropdownMenuItem, -Label, -Separator en -Group werken hierbinnen.",
      "Op touch bestaat rechtsklikken niet; zorg dat elke actie ook ergens anders bereikbaar is.",
    ],
  },
  {
    slug: "toast",
    name: "Toast",
    description: "Tijdelijke melding met toon, actie en automatische sluiting.",
    category: "Overlays",
    files: ["toast.tsx", "toast.css"],
    demos: [{ key: "toast-basic", title: "Tonen" }],
    props: ["ToastOptions", "ToastProviderProps"],
    notes: ["Zet ToastProvider één keer rond je app; daarna roep je overal useToast() aan."],
  },
  {
    slug: "command",
    name: "Command",
    description: "Zoek- en actiepalet met ⌘K-sneltoets.",
    category: "Overlays",
    files: ["command.tsx", "command.css"],
    dependsOn: ["dialog"],
    demos: [{ key: "command-basic", title: "Palet", align: "block" }],
    props: ["CommandProps", "CommandItemProps", "CommandDialogProps"],
  },
  {
    slug: "combobox",
    name: "Combobox",
    description: "Zoekbare keuzelijst met toetsenbordnavigatie.",
    category: "Formulieren",
    files: ["combobox.tsx", "combobox.css"],
    dependsOn: ["select"],
    demos: [{ key: "combobox-basic", title: "Zoeken en kiezen", align: "block" }],
    props: ["ComboboxProps", "ComboboxOption"],
  },
  {
    slug: "modal-manager",
    name: "ModalProvider",
    description: "Dialogs imperatief openen vanuit één register, met useModal().",
    category: "Overlays",
    files: ["modal-manager.tsx"],
    dependsOn: ["dialog"],
    demos: [{ key: "modal-manager-basic", title: "Register en useModal()", align: "block" }],
    props: ["ModalProviderProps", "ModalApi"],
    notes: [
      "Handig zodra je veel dialogs vanuit menu's, tabellen of een store opent. De declaratieve Dialog blijft gewoon werken — dit is een extra laag, geen vervanging.",
      "Elk geregistreerd component krijgt zijn eigen props plus onClose en rendert zelf een Dialog of Drawer. Met createModals() weet TypeScript welke props bij welke soort horen.",
    ],
  },
  {
    slug: "calendar",
    name: "Calendar",
    description: "Maandkalender met enkelvoudige, bereik- en meervoudige selectie.",
    category: "Datum & planning",
    files: ["calendar.tsx", "calendar.css", "../lib/date.ts"],
    demos: [
      { key: "calendar-basic", title: "Eén datum en een periode", align: "block" },
      { key: "calendar-multiple", title: "Meerdere dagen", align: "block" },
    ],
    props: ["CalendarProps"],
    notes: [
      "Toetsenbord: pijltjes verplaatsen per dag of week, Home en End springen naar het begin of einde van de week, PageUp en PageDown wisselen van maand (met Shift van jaar).",
      "De datumhulpfuncties in lib/date.ts worden meegekopieerd en zijn ook los bruikbaar: startOfWeek, getISOWeek, formatDateRange, parseTime en meer.",
    ],
  },
  {
    slug: "date-picker",
    name: "DatePicker",
    description: "Datum of periode kiezen in een popover, met snelkeuzes.",
    category: "Datum & planning",
    files: ["date-picker.tsx", "date-picker.css"],
    dependsOn: ["calendar", "popover", "field"],
    demos: [{ key: "datepicker-basic", title: "Datum en periode", align: "block" }],
    props: ["DatePickerProps", "DateRangePickerProps"],
  },
  {
    slug: "time-field",
    name: "TimeField",
    description: "Tijd invoeren met slimme parsing, stappen en tijdslotsuggesties.",
    category: "Datum & planning",
    files: ["time-field.tsx", "time-field.css", "../lib/date.ts"],
    dependsOn: ["field"],
    demos: [{ key: "timefield-basic", title: "Tijd en tijdsduur", align: "block" }],
    props: ["TimeFieldProps", "TimeRangeFieldProps"],
    notes: [
      "Het veld begrijpt 9, 930, 9.30 en 09:30 en formatteert bij het verlaten van het veld. Pijltjes omhoog en omlaag springen per stap.",
    ],
  },
  {
    slug: "period-nav",
    name: "PeriodNav",
    description: "Vorige en volgende door weken, maanden of elke andere periode.",
    category: "Datum & planning",
    files: ["period-nav.tsx", "period-nav.css"],
    demos: [{ key: "periodnav-basic", title: "Weken doorlopen", align: "block" }],
    props: ["PeriodNavProps"],
  },
  {
    slug: "week-schedule",
    name: "WeekSchedule",
    description: "Weekplanning met uurraster, overlappende blokken en drag & drop.",
    category: "Datum & planning",
    files: ["week-schedule.tsx", "week-schedule.css", "../lib/date.ts"],
    demos: [
      { key: "schedule-basic", title: "Rooster met verslepen", align: "block" },
      { key: "agenda-views", title: "Vier weergaven, één datamodel", description: "Dezelfde resources en events in ResourceColumns, WeekSchedule, TimeSlotList en Swimlanes.", align: "block" },
    ],
    props: ["WeekScheduleProps", "ScheduleEvent", "ScheduleDay"],
    notes: [
      "Slepen, verkleinen en verlengen zijn zelf geschreven met pointer events — geen dnd-kit of react-beautiful-dnd.",
      "Overlappende diensten worden automatisch naast elkaar gelegd; blokken met locked blijven staan.",
    ],
  },
  {
    slug: "resource-columns",
    name: "ResourceColumns",
    description: "Dagagenda met een kolom per arts, kamer of medewerker.",
    category: "Datum & planning",
    files: ["resource-columns.tsx", "resource-columns.css", "../lib/schedule.ts"],
    demos: [{ key: "resource-columns-basic", title: "Kolommen, met inklappen", align: "block" }],
    props: ["ResourceColumnsProps"],
    notes: [
      "Met collapseEmpty krimpen kolommen zonder afspraken tot een smalle rail, zodat de drukke kolommen alle ruimte krijgen.",
    ],
  },
  {
    slug: "swimlanes",
    name: "Swimlanes",
    description: "De agenda op zijn kant: een baan per resource, tijd van links naar rechts.",
    category: "Datum & planning",
    files: ["swimlanes.tsx", "swimlanes.css", "../lib/schedule.ts"],
    demos: [{ key: "swimlanes-basic", title: "Kamers en zalen", align: "block" }],
    props: ["SwimlanesProps"],
    notes: [
      "Gaten en overlappingen tussen mensen of ruimtes vallen hier het snelst op. De namenkolom blijft links staan tijdens het horizontaal scrollen.",
    ],
  },
  {
    slug: "time-slot-list",
    name: "TimeSlotList",
    description: "De dag als verticale tijdlijn, met kaartjes per tijdstip.",
    category: "Datum & planning",
    files: ["time-slot-list.tsx", "time-slot-list.css", "../lib/schedule.ts"],
    demos: [{ key: "timeslot-basic", title: "Dagoverzicht", align: "block" }],
    props: ["TimeSlotListProps"],
    notes: ["Werkt goed op smalle schermen: de kaartjes vullen automatisch de beschikbare breedte."],
  },
  {
    slug: "stat",
    name: "Stat",
    description: "KPI-tegel met waarde, icoon, trend en grafiekje.",
    category: "Data",
    files: ["stat.tsx", "stat.css"],
    dependsOn: ["chart"],
    demos: [{ key: "stat-basic", title: "KPI-raster", align: "block" }],
    props: ["StatProps"],
  },
  {
    slug: "data-pill",
    name: "DataPill",
    description: "Compacte meetwaarde: label, waarde en eenheid op één regel.",
    category: "Data",
    files: ["data-pill.tsx", "data-pill.css"],
    demos: [{ key: "datapill-basic", title: "Metingen en kerngegevens", align: "block" }],
    props: ["DataPillProps"],
  },
  {
    slug: "list-row",
    name: "ListRow",
    description: "Rij in een lijst: afspraak, document, gebruiker of melding.",
    category: "Data",
    files: ["list-row.tsx", "list-row.css"],
    demos: [{ key: "list-row-basic", title: "Agenda en documenten", align: "block" }],
    props: ["ListRowProps", "RowListProps", "RowIconProps"],
    notes: [
      "Alles behalve de titel is optioneel: lead, leading, subtitle, trailing en actions. Daardoor past dezelfde rij in een agenda, een documentenlijst of een meldingenpaneel.",
      "RowList bepaalt de vorm: bordered geeft één kaart met scheidingslijnen, separated losse kaartjes.",
    ],
  },
  {
    slug: "task-item",
    name: "TaskItem",
    description: "Eén taak in een lijst: afvinken, prioriteit, labels en deeltaken.",
    category: "Data",
    files: ["task-item.tsx", "task-item.css"],
    dependsOn: ["confetti"],
    demos: [{ key: "task-basic", title: "Takenlijst", description: "Met Composer om iets toe te voegen.", align: "block" }],
    props: ["TaskItemProps", "TaskListProps"],
    notes: [
      "Afvinken laat confetti uit de knop springen. Zet celebrate={false} als je dat liever niet hebt.",
      "Verwijderen schuift de rij eerst weg en roept daarna pas onDelete aan, zodat je lijst niet plots verspringt.",
    ],
  },
  {
    slug: "chart",
    name: "Charts",
    description: "Sparkline, staaf-, lijn- en donutgrafiek — eigen SVG, geen bibliotheek.",
    category: "Data",
    files: ["chart.tsx", "chart.css"],
    demos: [
      { key: "chart-bar", title: "Staaf en lijn", align: "block" },
      { key: "chart-donut", title: "Donut en sparkline", align: "block" },
    ],
    props: ["BarChartProps", "LineChartProps", "DonutChartProps", "SparklineProps"],
  },
  {
    slug: "countdown",
    name: "Countdown",
    description: "Telt af naar een moment en stopt vanzelf op nul.",
    category: "Data",
    files: ["countdown.tsx", "countdown.css"],
    demos: [{ key: "countdown-basic", title: "Twee tellers", description: "Met labels, en compact met dubbele punten." }],
    props: ["CountdownProps"],
    notes: [
      "onComplete wordt precies één keer aangeroepen; daarna stopt de interval.",
      "Dagen verschijnen alleen zolang er meer dan 24 uur over is.",
    ],
  },
  {
    slug: "carousel",
    name: "Carousel",
    description: "Reeks kaarten of beelden met scroll-snap, knoppen en stippen.",
    category: "Data",
    files: ["carousel.tsx", "carousel.css"],
    dependsOn: ["button"],
    demos: [{ key: "carousel-basic", title: "Beelden bij een dossier", description: "Vegen, pijltjestoetsen of de knoppen; de browser doet het schuiven.", align: "block" }],
    props: ["CarouselProps", "CarouselItemProps"],
    notes: [
      "Het schuiven gebeurt met scroll-snap in plaats van met JavaScript: vegen op touch voelt daardoor natuurlijk aan.",
      "Met size per item toon je er meerdere tegelijk, bijvoorbeeld size=\"70%\" voor een glimp van de volgende.",
      "autoPlay staat standaard uit; zet het alleen aan als de inhoud niet belangrijk is om te lezen.",
    ],
  },
  {
    slug: "timeline",
    name: "Timeline",
    description: "Verticale lijn met gebeurtenissen: audit-log, dossierverloop, statuswissels.",
    category: "Data",
    files: ["timeline.tsx", "timeline.css"],
    demos: [{ key: "timeline-basic", title: "Verloop van een dossier", description: "Stippen met icoon, tijd, auteur en een onderbroken lijn voor wat nog komt.", align: "block" }],
    props: ["TimelineProps", "TimelineItemProps"],
    notes: ["Niet te verwarren met TimeSlotList: die toont een dag in uren, dit toont gebeurtenissen na elkaar."],
  },
  {
    slug: "message-thread",
    name: "MessageThread",
    description: "Verloop van een gesprek: ticket, interne notities of chat.",
    category: "Data",
    files: ["message-thread.tsx", "message-thread.css"],
    demos: [{ key: "messagethread-basic", title: "Ticketgesprek", description: "Met dagscheiding, systeemregel, interne notitie en de Composer eronder.", align: "block" }],
    props: ["MessageThreadProps", "MessageProps"],
    notes: [
      "Combineert met Composer voor de invoer eronder.",
      "Een bericht met internal krijgt een amber bel met het label \"Interne notitie\" — handig voor wat de klant niet ziet.",
    ],
  },
  {
    slug: "qr-code",
    name: "QrCode",
    description: "Echte, scanbare QR-code; zelf geschreven encoder zonder dependencies.",
    category: "Data",
    files: ["qr-code.tsx", "qr-encode.ts", "qr-code.css"],
    demos: [{ key: "qr-basic", title: "Live code", description: "Typ een andere waarde of kies een ander foutcorrectieniveau.", align: "block" }],
    props: ["QrCodeProps"],
    notes: [
      "Byte-modus, versie 1 tot en met 10: tot 271 tekens bij niveau M. Daarboven volgt een duidelijke foutmelding.",
      "De code blijft altijd zwart op wit, ook in donkere modus — scanners hebben dat contrast nodig.",
      "De stille zone van 4 modules zit standaard in de afbeelding; maak ze niet kleiner.",
    ],
  },
  {
    slug: "toolbar",
    name: "Toolbar",
    description: "Knoppenrij met groepen, scheidingslijnen en aan/uit-knoppen.",
    category: "Navigatie",
    files: ["toolbar.tsx", "toolbar.css"],
    demos: [{ key: "toolbar-basic", title: "Opmaak en acties", align: "block" }],
    props: ["ToolbarProps", "ToolbarButtonProps"],
  },
  {
    slug: "section-header",
    name: "SectionHeader",
    description: "Compacte kop boven een blok, met gekleurd staafje en acties.",
    category: "Layout",
    files: ["section-header.tsx", "section-header.css"],
    demos: [{ key: "section-header-basic", title: "Tonen en formaten", align: "block" }],
    props: ["SectionHeaderProps"],
  },
  {
    slug: "entity-header",
    name: "EntityHeader",
    description: "Kop van een dossier: media, naam, kerngegevens, labels en acties.",
    category: "Layout",
    files: ["entity-header.tsx", "entity-header.css"],
    demos: [{ key: "entity-header-basic", title: "Dossierkop met tabs", align: "block" }],
    props: ["EntityHeaderProps", "EntityDetail"],
  },
  {
    slug: "sidebar",
    name: "Sidebar",
    description: "Navigatiekolom met secties, badges en inklapstand.",
    category: "Navigatie",
    files: ["sidebar.tsx", "sidebar.css"],
    dependsOn: ["app-shell"],
    demos: [
      { key: "sidebar-basic", title: "In een app-shell", align: "block" },
      { key: "sidebar-inverted", title: "Donkere rail", description: "tone=\"inverted\" — kleuren afgeleid van het Lorenthi UI-accent, werkt in beide thema's.", align: "block" },
    ],
    props: ["SidebarProps", "SidebarItemProps"],
  },
  {
    slug: "bottom-nav",
    name: "BottomNav",
    description: "Vaste navigatiebalk onderaan op mobiel, met iconen, labels en tellers.",
    category: "Navigatie",
    files: ["bottom-nav.tsx", "bottom-nav.css"],
    demos: [{ key: "bottomnav-basic", title: "Vier bestemmingen", description: "Tik om te wisselen; de teller zit op het icoon." }],
    props: ["BottomNavProps", "BottomNavItemProps"],
    notes: [
      "Verschijnt onder 860px breed. Met always toon je hem altijd, bijvoorbeeld in een telefoonvoorbeeld.",
      "Geef je pagina onderaan evenveel padding als de hoogte van de balk, anders valt de laatste inhoud eronder.",
    ],
  },
  {
    slug: "fab",
    name: "Fab",
    description: "Zwevende hoofdactie, met SpeedDial voor een waaier aan acties.",
    category: "Navigatie",
    files: ["fab.tsx", "fab.css"],
    dependsOn: ["button"],
    demos: [{ key: "fab-basic", title: "Knop en waaier", description: "Links een gewone Fab, rechts een SpeedDial die openklapt.", align: "block" }],
    props: ["FabProps", "SpeedDialProps", "SpeedDialActionProps"],
    notes: [
      "Standaard hangt de knop vast rechtsonder, met ruimte voor de iOS-homebalk. Met position static zet je hem gewoon in de stroom.",
      "Een Fab hoort één actie te zijn; heb je er meer, gebruik dan SpeedDial.",
    ],
  },
  {
    slug: "app-shell",
    name: "AppShell",
    description: "Layout met vaste zijbalk, bovenbalk en inhoudskolom.",
    category: "Layout",
    files: ["app-shell.tsx", "app-shell.css"],
    demos: [{ key: "appshell-basic", title: "Volledige shell", align: "block" }],
    props: ["AppShellProps", "TopbarProps", "PageHeaderProps"],
  },
  {
    slug: "aspect-ratio",
    name: "AspectRatio",
    description: "Houdt een vaste verhouding aan, zodat niets verspringt tijdens het laden.",
    category: "Layout",
    files: ["aspect-ratio.tsx", "aspect-ratio.css"],
    demos: [{ key: "aspectratio-basic", title: "Drie verhoudingen", description: "16:9, 4:3 en vierkant." }],
    props: ["AspectRatioProps"],
    notes: ["Een img, video of iframe erin vult automatisch het vlak met object-fit cover."],
  },
  {
    slug: "workspace",
    name: "Workspace",
    description: "Werkblad met smalle rails links en rechts naast de inhoud.",
    category: "Layout",
    files: ["workspace.tsx", "workspace.css"],
    dependsOn: ["section-header"],
    demos: [{ key: "workspace-basic", title: "Drie kolommen", align: "block" }],
    props: ["WorkspaceProps", "WorkspaceRailProps"],
    notes: [
      "Het breekpunt (stackAt) kijkt naar de breedte van het werkblad zelf via een container query, niet naar het venster. Zo stapelt het ook correct wanneer het werkblad in een smalle kolom staat, en blijft het pure CSS: geen flits bij het laden, geen meting in JavaScript.",
    ],
  },
  {
    slug: "resizable",
    name: "ResizableGroup",
    description: "Panelen met een sleepbare scheiding ertussen.",
    category: "Layout",
    files: ["resizable.tsx", "resizable.css"],
    demos: [{ key: "resizable-basic", title: "Lijst en detail", description: "Sleep de scheiding, of gebruik de pijltjestoetsen (Shift voor stappen van 10%).", align: "block" }],
    props: ["ResizableGroupProps", "ResizablePanelProps", "ResizableHandleProps"],
    notes: [
      "Panelen en grepen krijgen een index mee, omdat ze in dezelfde rij door elkaar staan: greep index={0} verdeelt paneel 0 en 1.",
      "Maten zijn percentages, dus de verdeling blijft kloppen als het venster verandert.",
    ],
  },
  {
    slug: "scroll-area",
    name: "ScrollArea",
    description: "Scrollbaar vlak met een smalle balk en vervaging aan de randen.",
    category: "Layout",
    files: ["scroll-area.tsx", "scroll-area.css"],
    demos: [{ key: "scrollarea-basic", title: "Dagoverzicht", description: "De vervaging boven en onder verschijnt alleen als daar nog inhoud zit." }],
    props: ["ScrollAreaProps"],
    notes: [
      "Dit is de echte scrollbalk van de browser, alleen anders opgemaakt: vegen, scrollwiel en toetsenbord blijven werken zoals gebruikers gewend zijn.",
      "De vervaging gebruikt mask-image; zet fade uit als je inhoud met eigen maskers werkt.",
    ],
  },
  {
    slug: "mockup",
    name: "Mockup",
    description: "Een scherm in een browser-, venster- of telefoonframe zetten.",
    category: "Layout",
    files: ["mockup.tsx", "mockup.css"],
    demos: [{ key: "mockup-basic", title: "Drie frames", description: "MockupBrowser, MockupWindow en MockupPhone met echte inhoud erin.", align: "block" }],
    props: ["MockupBrowserProps", "MockupWindowProps", "MockupPhoneProps"],
    notes: [
      "Bedoeld voor documentatie, release-notes en marketingpagina's — niet voor de app zelf.",
      "MockupPhone schaalt op breedte; de hoogte volgt uit ratio (standaard 19,5:9).",
      "Met screen of wallpaper geef je het hele scherm een achtergrond; de statusbalk wordt dan vanzelf wit op donker. Zonder die props volgt het scherm het thema van de site.",
    ],
  },
  {
    slug: "auth-layout",
    name: "AuthLayout",
    description: "Aanmeldscherm: merkpaneel, kaart, scheiding en SSO-knoppen.",
    category: "Layout",
    files: ["auth-layout.tsx", "auth-layout.css"],
    demos: [
      { key: "auth-split", title: "Split met itsme® en eID", align: "block" },
      { key: "auth-centered", title: "Gecentreerd", align: "block" },
    ],
    props: ["AuthLayoutProps", "AuthCardProps", "AuthDividerProps", "SsoButtonProps"],
    notes: [
      "Het zijpaneel verdwijnt onder 900px, dus je hoeft geen apart mobiel scherm te bouwen.",
      "SsoButton neemt een merkkleur via color — die kleurt het icoonvlak, de rand bij hover en de pijl, zonder ergens een kleur hard te zetten.",
    ],
  },
  {
    slug: "confetti",
    name: "ConfettiBurst",
    description: "Kleine explosie van snippers bij iets dat af is.",
    category: "Feedback",
    files: ["confetti.tsx", "confetti.css"],
    demos: [{ key: "confetti-basic", title: "Vieren" }],
    props: ["ConfettiBurstProps"],
    notes: [
      "Rendert één keer en ruimt zichzelf op via onDone. Bij “verminderde beweging” gebeurt er niets.",
      "De kleuren komen standaard uit de thematokens, dus de confetti past zich aan licht en donker aan.",
    ],
  },
  {
    slug: "slider",
    name: "Slider",
    description: "Schuifregelaar met waardeweergave en tonen.",
    category: "Formulieren",
    files: ["slider.tsx", "slider.css"],
    demos: [{ key: "slider-basic", title: "Varianten", align: "block" }],
    props: ["SliderProps"],
  },
  {
    slug: "otp-input",
    name: "OtpInput",
    description: "Invoer van een verificatiecode, één teken per vakje.",
    category: "Formulieren",
    files: ["otp-input.tsx", "otp-input.css"],
    demos: [{ key: "otp-basic", title: "Zes cijfers", align: "block" }],
    props: ["OtpInputProps"],
  },
  {
    slug: "file-drop",
    name: "FileDrop",
    description: "Sleepzone voor bestanden, met bestandslijst.",
    category: "Formulieren",
    files: ["file-drop.tsx", "file-drop.css"],
    demos: [{ key: "filedrop-basic", title: "Uploadzone", align: "block" }],
    props: ["FileDropProps", "FileItemProps"],
  },
  {
    slug: "swatch-picker",
    name: "SwatchPicker",
    description: "Kleur kiezen uit een rij stalen, met optionele eigen kleur.",
    category: "Formulieren",
    files: ["swatch-picker.tsx", "swatch-picker.css"],
    demos: [{ key: "swatch-basic", title: "Stalen", align: "block" }],
    props: ["SwatchPickerProps"],
    notes: [
      "Elke geldige CSS-kleur mag, dus je kan er ook tokens in stoppen: var(--accent), var(--violet) …",
    ],
  },
  {
    slug: "avatar-upload",
    name: "AvatarUpload",
    description: "Profielfoto kiezen, bijsnijden en verkleinen in de browser.",
    category: "Formulieren",
    files: ["avatar-upload.tsx", "avatar-upload.css", "../lib/image.ts"],
    dependsOn: ["avatar"],
    demos: [{ key: "avatar-upload-basic", title: "Profiel bewerken", align: "block" }],
    props: ["AvatarUploadProps"],
    notes: [
      "De foto wordt vierkant bijgesneden en naar outputSize verkleind op een canvas. Je krijgt een compacte data-URL terug, klaar om te bewaren.",
    ],
  },
  {
    slug: "composer",
    name: "Composer",
    description: "Invoerbalk om snel iets toe te voegen, met microfoon en snelkeuzes.",
    category: "Formulieren",
    files: ["composer.tsx", "composer.css"],
    dependsOn: ["voice-button"],
    demos: [{ key: "composer-basic", title: "Toevoegen met snelkeuzes", align: "block" }],
    props: ["ComposerProps"],
    notes: [
      "Enter voegt toe en houdt de focus in het veld, zodat je meerdere regels na elkaar kan intypen.",
      "Kinderen van Composer komen onder het veld te staan — handig voor deadlines, lijsten of labels.",
    ],
  },
  {
    slug: "rich-editor",
    name: "RichEditor",
    description: "Tekstvak met opmaakknoppen: vet, cursief, markeren en lijsten.",
    category: "Formulieren",
    files: ["rich-editor.tsx", "rich-editor.css"],
    demos: [{ key: "richeditor-basic", title: "Verslag met opmaak", description: "Selecteer tekst en gebruik de werkbalk of Ctrl+B / Ctrl+I / Ctrl+U.", align: "block" }],
    props: ["RichEditorProps"],
    notes: [
      "De waarde is HTML. Komt ze van een gebruiker, saneer ze dan server-side voor je ze elders weer toont.",
      "Plakken gebeurt standaard als platte tekst, zodat opmaak uit Word of een webpagina niet meelift.",
      "Gebouwd op document.execCommand. Dat is als verouderd gemarkeerd, maar werkt in elke browser en heeft geen standaardopvolger.",
    ],
  },
  {
    slug: "voice-button",
    name: "VoiceButton",
    description: "Microfoonknop op de spraakherkenning van de browser.",
    category: "Formulieren",
    files: ["voice-button.tsx", "voice-button.css", "../lib/use-voice.ts"],
    demos: [{ key: "voice-basic", title: "Inspreken", description: "Werkt in Chrome en Edge; elders valt de knop netjes terug.", align: "block" }],
    props: ["VoiceButtonProps", "UseVoiceOptions"],
    notes: [
      "Spraakherkenning zit niet in elke browser. Met whenUnsupported kies je zelf of de knop verdwijnt, grijs wordt of gewoon blijft staan.",
      "useVoice geeft je hetzelfde zonder knop: { listening, supported, start, stop, toggle }.",
    ],
  },
  {
    slug: "pulse-dot",
    name: "PulseDot",
    description: "Statusbolletje met kloppende halo, voor live of bezet.",
    category: "Feedback",
    files: ["pulse-dot.tsx", "pulse-dot.css"],
    demos: [{ key: "pulsedot-basic", title: "Statussen", align: "block" }],
    props: ["PulseDotProps"],
  },
  {
    slug: "theme",
    name: "Theme",
    description: "Licht/donker met ThemeProvider, useTheme en ThemeToggle.",
    category: "Layout",
    files: ["theme.tsx", "theme.css"],
    demos: [
      { key: "theme-basic", title: "Schakelen", align: "block" },
      { key: "density-basic", title: "Dichtheid", description: "Compact, normaal of ruim — alle componenten schalen mee.", align: "block" },
    ],
    props: ["ThemeProviderProps", "ThemeToggleProps", "DensityToggleProps"],
    notes: [
      "Plaats ThemeScript in je head zodat het opgeslagen thema al vóór de eerste paint staat — geen witte flits bij het laden.",
      "De dichtheid staat in één token: --density. Elke hoogte en padding in de library is calc(Npx * var(--density)), dus compact en ruim werken meteen door in alle componenten.",
    ],
  },
  {
    slug: "motion-drawer",
    name: "MotionDrawerContent",
    description: "Drawer met veerbeweging, uitgaande animatie en wegvegen om te sluiten.",
    category: "Motion",
    files: ["../motion/motion-drawer.tsx", "../motion/motion.css"],
    dependsOn: ["drawer", "button"],
    requires: ["motion"],
    demos: [{ key: "motiondrawer-basic", title: "Sheet met veeg", description: "Sleep het paneel opzij of aan het greepje naar beneden." }],
    props: ["MotionDrawerContentProps"],
    notes: [
      "Vervangt alleen DrawerContent. Drawer, DrawerHeader, DrawerBody en DrawerFooter blijven dezelfde.",
      "Respecteert prefers-reduced-motion: dan vervaagt het paneel in plaats van te schuiven en staat slepen uit.",
    ],
  },
  {
    slug: "otp-verification",
    name: "OtpVerification",
    description: "Verificatiekaart die zichzelf controleert: rij, raster, samensmelten, bevestiging.",
    category: "Motion",
    files: ["../motion/otp-verification.tsx", "../motion/motion.css"],
    requires: ["motion"],
    demos: [
      { key: "otpverification-basic", title: "De volledige animatie", description: "Typt zichzelf in en herhaalt; typ gerust mee." },
      { key: "otpverification-verify", title: "Met echte controle", description: "onVerify beslist; een foute code schudt en wist zichzelf.", align: "block" },
      { key: "otpverification-orbit", title: "Variant orbit", description: "De cijfers draaien rond het midden terwijl je backend antwoordt, met tellertje en knop." },
    ],
    props: ["OtpVerificationProps", "OtpVerificationTexts"],
    notes: [
      "onVerify mag async zijn: de raster-animatie loopt door terwijl je backend antwoordt. false of een fout geeft de foutstatus.",
      "Zonder demoCode blijft de kaart stil staan wachten op invoer — demoCode, autoPlay en loop zijn er alleen voor voorbeelden.",
      "OtpInput is het kale invoerveld; dit is de volledige kaart met animatie eromheen.",
      "variant=\"orbit\" laat de vakjes rond het midden draaien in plaats van naar een raster te schuiven; action, icon en resendAfter voegen de knop, het icoontje en het tellertje toe.",
      "Bij \"verminderde beweging\" vervallen de veren en de snippers; de statuswissels blijven.",
    ],
  },
  {
    slug: "upload-button",
    name: "UploadButton",
    description: "Bestandsveld waarvan de knop over het veld openklapt en zich vult met de voortgang.",
    category: "Motion",
    files: ["../motion/upload-button.tsx", "../motion/motion.css"],
    requires: ["motion"],
    demos: [
      { key: "uploadbutton-basic", title: "Kiezen en uploaden" },
      { key: "uploadbutton-real", title: "Met een echte upload", description: "onUpload krijgt het bestand en een functie voor de voortgang.", align: "block" },
    ],
    props: ["UploadButtonProps", "UploadButtonTexts"],
    notes: [
      "Zonder onUpload loopt er een nep-voortgang van demoDuration ms — handig voor voorbeelden en prototypes.",
      "resetAfter={false} laat de knop op \"klaar\" staan; anders springt hij na die tijd terug naar het begin.",
    ],
  },
  {
    slug: "payment-checkout",
    name: "PaymentCheckout",
    description: "Kaartgegevens invullen met een kaart die meeschrijft, omdraait voor de CVC en de betaling afrondt.",
    category: "Motion",
    files: ["../motion/payment-checkout.tsx", "../motion/motion.css"],
    dependsOn: ["field", "input", "button"],
    requires: ["motion"],
    demos: [
      { key: "paymentcheckout-basic", title: "De volledige flow", description: "Vult zichzelf in en betaalt; de kaart blijft over tijdens het verwerken.", align: "block" },
      { key: "paymentcheckout-real", title: "Zelf invullen", description: "onPay beslist of de betaling lukt.", align: "block" },
    ],
    props: ["PaymentCheckoutProps", "PaymentValues", "PaymentCheckoutTexts"],
    notes: [
      "Het merk (visa, mastercard, amex) volgt uit de eerste cijfers; amex krijgt de 4-6-5-groepering.",
      "De kaart draait om zodra het CVC-veld focus krijgt en weer terug bij blur.",
      "Het bedrag wordt opgemaakt met Intl.NumberFormat — geef currency en locale mee voor een andere munt.",
      "De kaart gebruikt de accentkleur van je thema als verloop; één token aanpassen herkleurt ze.",
    ],
  },
  {
    slug: "send-button",
    name: "SendButton",
    description: "De knop vouwt zich tot een papieren vliegtuigje dat wegvliegt, en komt terug als \"verzonden\".",
    category: "Motion",
    files: ["../motion/send-button.tsx", "../motion/use-action.ts", "../motion/motion.css"],
    requires: ["motion"],
    demos: [{ key: "sendbutton-basic", title: "Versturen en mislukken" }],
    props: ["SendButtonProps"],
    notes: ["onSend mag async zijn; false of een fout geeft de rode staat. Met resetAfter={false} blijft het resultaat staan."],
  },
  {
    slug: "order-button",
    name: "OrderButton",
    description: "Bestelknop waar een bestelwagen doorheen rijdt voor ze op groen \"besteld\" springt.",
    category: "Motion",
    files: ["../motion/order-button.tsx", "../motion/use-action.ts", "../motion/motion.css"],
    requires: ["motion"],
    demos: [{ key: "orderbutton-basic", title: "Bestellen" }],
    props: ["OrderButtonProps"],
    notes: ["De rit duurt 1,5 seconde; een sneller antwoord van je backend wacht netjes tot de wagen buiten beeld is."],
  },
  {
    slug: "add-to-cart-button",
    name: "AddToCartButton",
    description: "Knop die samentrekt tot een mandje, het artikel erin laat vallen en de teller optelt.",
    category: "Motion",
    files: ["../motion/add-to-cart-button.tsx", "../motion/use-action.ts", "../motion/motion.css"],
    requires: ["motion"],
    demos: [{ key: "addtocart-basic", title: "Toevoegen" }],
    props: ["AddToCartButtonProps"],
    notes: ["De teller werkt controlled (count + onCountChange) of uncontrolled (defaultCount); hint={null} laat de regel eronder weg."],
  },
  {
    slug: "share-button",
    name: "ShareButton",
    description: "Deelknop die openwaaiert naar je kanalen en de link op het klembord zet.",
    category: "Motion",
    files: ["../motion/share-button.tsx", "../motion/motion.css"],
    requires: ["motion"],
    demos: [{ key: "sharebutton-basic", title: "Kanalen kiezen" }],
    props: ["ShareButtonProps", "ShareChannel"],
    notes: [
      "Een kanaal met href opent een venster ({url} wordt vervangen); zonder href wordt de link gekopieerd.",
      "Escape of een klik ernaast klapt de waaier weer dicht.",
    ],
  },
  {
    slug: "delete-button",
    name: "DeleteButton",
    description: "De vuilnisbak schuift over het label heen en eet het op, daarna volgt de bevestiging.",
    category: "Motion",
    files: ["../motion/delete-button.tsx", "../motion/use-action.ts", "../motion/motion.css"],
    requires: ["motion"],
    demos: [{ key: "deletebutton-basic", title: "Vol en zacht" }],
    props: ["DeleteButtonProps"],
    notes: ["Voor iets dat echt weg is: combineer met AlertDialog om te laten bevestigen vóór onDelete draait."],
  },
  {
    slug: "layout",
    name: "Stack, Row & Grid",
    description: "Layout-primitieven: Container, Stack, Row, Grid en Spacer op één afstandsschaal.",
    category: "Layout",
    files: ["layout.tsx", "layout.css"],
    demos: [{ key: "layout-basic", title: "De vijf samen", align: "block" }],
    props: ["ContainerProps", "StackProps", "RowProps", "GridProps", "SpacerProps"],
    notes: [
      "gap gaat van xs tot xl en gebruikt dezelfde schaal als de rest van de library, dus geen losse pixelwaarden in je markup.",
      "Grid zonder cols schikt zijn kolommen vanzelf: min bepaalt hoe smal een kolom mag worden.",
      "Met as render je een ander element, bijvoorbeeld <Stack as=\"ul\"> voor een echte lijst.",
    ],
    isNew: true,
  },
  {
    slug: "text",
    name: "Text",
    description: "Eén component voor alle tekst: variant, toon, gewicht, uitlijning en afkappen.",
    category: "Basis",
    files: ["text.tsx", "text.css"],
    demos: [{ key: "text-basic", title: "Varianten en afkappen", align: "block" }],
    props: ["TextProps"],
    notes: [
      "De variant kiest ook het element: h2 wordt een <h2>, body een <p>. Met as overschrijf je dat.",
      "truncate kapt één regel af, lines={2} kapt af na een vast aantal regels.",
    ],
    isNew: true,
  },
  {
    slug: "key-value",
    name: "KeyValueList",
    description: "Labels met hun waarde, zoals in een dossierkop of detailpaneel.",
    category: "Data",
    files: ["key-value.tsx", "key-value.css"],
    demos: [{ key: "keyvalue-basic", title: "Horizontaal en in kolommen", align: "block" }],
    props: ["KeyValueListProps", "KeyValueProps"],
    notes: [
      "Rendert een echte <dl> met <dt> en <dd>, dus schermlezers lezen label en waarde als paar.",
      "Een lege waarde wordt automatisch een streepje; met empty kies je zelf wat er staat.",
    ],
    isNew: true,
  },
  {
    slug: "filter-panel",
    name: "FilterPanel",
    description: "Filterkolom met groepen, tellers, avatars, \"toon meer\" en een wisknop.",
    category: "Navigatie",
    files: ["filter-panel.tsx", "filter-panel.css"],
    demos: [{ key: "filterpanel-basic", title: "Dossiers filteren", align: "block" }],
    props: ["FilterPanelProps", "FilterGroupProps", "FilterOptionProps"],
    notes: [
      "maxVisible zet de rest van een groep achter \"toon meer\"; collapsible maakt de hele groep inklapbaar.",
      "FilterOption werkt als checkbox of radio en kent ook de derde staat (indeterminate) voor een groep die half aan staat.",
      "tone=\"inverted\" geeft dezelfde donkere rail als de Sidebar.",
    ],
    isNew: true,
  },
  {
    slug: "reorder-list",
    name: "ReorderList",
    description: "Lijst waarvan je de volgorde sleept, met of zonder greepje.",
    category: "Motion",
    files: ["../motion/reorder-list.tsx", "../motion/motion.css"],
    requires: ["motion"],
    demos: [{ key: "reorder-basic", title: "Taken herschikken", description: "Sleep een rij naar boven of beneden; de rest schuift mee.", align: "block" }],
    props: ["ReorderListProps", "ReorderListItemProps"],
    notes: [
      "Elke waarde in values moet uniek zijn; motion gebruikt ze als identiteit.",
      "Met handle sleep je alleen aan het greepje, zodat knoppen in de rij klikbaar blijven.",
    ],
  },
  {
    slug: "motion-segmented",
    name: "MotionSegmented",
    description: "Segmented waarbij de actieve achtergrond meeschuift in plaats van verspringt.",
    category: "Motion",
    files: ["../motion/motion-segmented.tsx", "../motion/motion.css"],
    dependsOn: ["segmented"],
    requires: ["motion"],
    demos: [{ key: "motionsegmented-basic", title: "Meeschuivende indicator", description: "Zelfde API als Segmented." }],
    props: ["MotionSegmentedProps"],
    notes: ["Dezelfde props als Segmented; layoutId alleen nodig als er meerdere naast elkaar staan."],
  },
];

export function componentBySlug(slug: string): ComponentEntry | undefined {
  return COMPONENTS.find((component) => component.slug === slug);
}

export function componentsByCategory(): Array<{ category: string; items: ComponentEntry[] }> {
  return CATEGORIES.map((category) => ({
    category,
    items: COMPONENTS.filter((component) => component.category === category),
  })).filter((group) => group.items.length > 0);
}

export function newComponents(): ComponentEntry[] {
  return COMPONENTS.filter((component) => component.isNew);
}

export function updatedComponents(): ComponentEntry[] {
  return COMPONENTS.filter((component) => component.isUpdated && !component.isNew);
}

/** Welk label hoort bij dit item: "new", "updated" of geen. */
export function entryTag(entry: { isNew?: boolean; isUpdated?: boolean }): "new" | "updated" | null {
  if (entry.isNew) return "new";
  if (entry.isUpdated) return "updated";
  return null;
}
