export interface DemoEntry {
  /** Sleutel van het demobestand in /demos. */
  key: string;
  title: string;
  description?: string;
  /** Inhoud links uitlijnen in plaats van centreren. */
  align?: "center" | "start" | "block";
  /** Toont een "nieuw"-label bij deze demo. */
  isNew?: boolean;
  /** Toont een "bijgewerkt"-label bij deze demo. Wordt genegeerd als isNew aanstaat. */
  isUpdated?: boolean;
}

export interface ComponentEntry {
  slug: string;
  name: string;
  description: string;
  category: string;
  /** Bestanden uit packages/ui die dit component nodig heeft. */
  files: string[];
  /** Andere componenten die mee gekopieerd worden. */
  dependsOn?: string[];
  /** npm-packages die dit component nodig heeft. Alleen de motion-laag gebruikt dit. */
  requires?: string[];
  demos: DemoEntry[];
  /** Namen van interfaces waarvan de props-tabel getoond wordt. */
  props?: string[];
  notes?: string[];
  /** Toont een "nieuw"-label in de navigatie en op de pagina. */
  isNew?: boolean;
  /** Toont een "bijgewerkt"-label in de navigatie en op de pagina. Wordt genegeerd als isNew aanstaat. */
  isUpdated?: boolean;
}

export const CATEGORIES = [
  "Basis",
  "Formulieren",
  "Overlays",
  "Navigatie",
  "Datum & planning",
  "Data",
  "Feedback",
  "Layout",
  "AI",
  "Motion",
] as const;

/*
 * Labels per release: bij elke release gaan ALLE isNew- en isUpdated-vlaggen eruit,
 * en krijgen alleen de componenten van díé release er weer een. Zo staat er nooit
 * "nieuw" op iets van drie releases geleden.
 *
 * Elke stap van de opbouw voegt hier componenten toe.
 * Houd de opmaak aan (twee spaties + "{" op een eigen regel): scripts/build-registry.mjs leest dit bestand.
 */
export const COMPONENTS: ComponentEntry[] = [
  {
    slug: "button",
    name: "Button",
    description: "Knop met zes varianten, drie maten, iconen en laadstatus.",
    category: "Basis",
    files: ["button.tsx", "button.css"],
    dependsOn: ["spinner"],
    demos: [
      { key: "button-variants", title: "Varianten" },
      { key: "button-sizes", title: "Maten en iconen" },
      { key: "button-states", title: "Laden, uitgeschakeld en groep" },
    ],
    props: ["ButtonProps"],
    notes: [
      "Met asChild rendert de knop jouw eigen element — bijvoorbeeld een link of next/link — met behoud van alle stijl en states.",
    ],
  },
  {
    slug: "badge",
    name: "Badge",
    description: "Compact label voor status, categorie of telling.",
    category: "Basis",
    files: ["badge.tsx", "badge.css"],
    demos: [
      { key: "badge-tones", title: "Tonen" },
      { key: "badge-usage", title: "Met stip en icoon" },
    ],
    props: ["BadgeProps"],
  },
  {
    slug: "card",
    name: "Card",
    description: "Basiscontainer met kop, inhoud en voettekst.",
    category: "Basis",
    files: ["card.tsx", "card.css"],
    demos: [{ key: "card-basic", title: "Opbouw", align: "block" }],
    props: ["CardProps"],
  },
  {
    slug: "spinner",
    name: "Spinner",
    description: "Ronddraaiende laadindicator die de tekstkleur erft.",
    category: "Basis",
    files: ["spinner.tsx", "spinner.css"],
    demos: [{ key: "spinner-basic", title: "Maten" }],
    props: ["SpinnerProps"],
  },
  {
    slug: "icon",
    name: "Icon",
    description: "Eigen icon set: één stroke-based glyph per naam.",
    category: "Basis",
    files: ["../icons/icon.tsx", "../icons/icons.ts"],
    demos: [{ key: "icon-gallery", title: "Volledige set", align: "block" }],
    props: ["IconProps"],
  },
  {
    slug: "separator",
    name: "Separator",
    description: "Scheidingslijn, horizontaal of verticaal, met optioneel label.",
    category: "Basis",
    files: ["separator.tsx", "separator.css"],
    demos: [{ key: "separator-basic", title: "Varianten", align: "block" }],
    props: ["SeparatorProps"],
  },
  {
    slug: "kbd",
    name: "Kbd",
    description: "Toetsaanslag of sneltoets tonen.",
    category: "Basis",
    files: ["kbd.tsx", "kbd.css"],
    demos: [{ key: "kbd-basic", title: "Sneltoetsen" }],
    props: ["KbdProps"],
  },
  {
    slug: "skeleton",
    name: "Skeleton",
    description: "Laadplaceholder met shimmer.",
    category: "Basis",
    files: ["skeleton.tsx", "skeleton.css"],
    demos: [{ key: "skeleton-basic", title: "Vormen", align: "block" }],
    props: ["SkeletonProps"],
  },
  {
    slug: "avatar",
    name: "Avatar",
    description: "Foto of initialen, met statusstip en groepsweergave.",
    category: "Basis",
    files: ["avatar.tsx", "avatar.css"],
    demos: [{ key: "avatar-basic", title: "Maten, status en groep" }],
    props: ["AvatarProps", "AvatarGroupProps"],
    notes: ["Met initials zet je zelf de letters, bijvoorbeeld een trigram van drie tekens in plaats van de afgeleide initialen."],
  },
  {
    slug: "chip",
    name: "Chip",
    description: "Klikbaar filterlabel, of een verwijderbare tag.",
    category: "Basis",
    files: ["chip.tsx", "chip.css"],
    demos: [{ key: "chip-basic", title: "Filters en tags", align: "block" }],
    props: ["ChipProps", "ChipGroupProps"],
    notes: ["Badge is een label om te lezen, Chip is er een om op te klikken. Met onRemove wordt het een tag met kruisje."],
  },
  {
    slug: "copy-button",
    name: "CopyButton",
    description: "Kopieert een waarde en bevestigt dat kort met een vinkje.",
    category: "Basis",
    files: ["copy-button.tsx", "copy-button.css"],
    demos: [{ key: "copybutton-basic", title: "Kopiëren", align: "block" }],
    props: ["CopyButtonProps"],
  },
  {
    slug: "label",
    name: "Label",
    description: "Bijschrift voor een formulierveld, met verplicht-markering.",
    category: "Formulieren",
    files: ["label.tsx", "label.css"],
    demos: [{ key: "label-basic", title: "Standaard", align: "block" }],
    props: ["LabelProps"],
  },
  {
    slug: "input",
    name: "Input",
    description: "Tekstveld met iconen, addon, maten en foutstatus.",
    category: "Formulieren",
    files: ["input.tsx", "input.css"],
    dependsOn: ["field"],
    demos: [
      { key: "input-basic", title: "Maten en varianten", align: "block" },
      { key: "input-affix", title: "Icoon, suffix en addon", align: "block" },
    ],
    props: ["InputProps"],
  },
  {
    slug: "textarea",
    name: "Textarea",
    description: "Meerregelig tekstveld, optioneel meegroeiend.",
    category: "Formulieren",
    files: ["textarea.tsx", "textarea.css"],
    dependsOn: ["field"],
    demos: [{ key: "textarea-basic", title: "Standaard en meegroeiend", align: "block" }],
    props: ["TextareaProps"],
  },
  {
    slug: "field",
    name: "Field",
    description: "Koppelt label, hint en foutmelding aan één invoerveld.",
    category: "Formulieren",
    files: ["field.tsx", "field.css"],
    dependsOn: ["label"],
    demos: [{ key: "field-basic", title: "Label, hint en fout", align: "block" }],
    props: ["FieldProps"],
    notes: [
      "Field zet automatisch id, aria-describedby en aria-invalid op het veld erin — je hoeft niets handmatig te koppelen.",
    ],
  },
  {
    slug: "fieldset",
    name: "Fieldset",
    description: "Groepje bij elkaar horende velden met een gedeelde titel.",
    category: "Formulieren",
    files: ["fieldset.tsx", "fieldset.css"],
    demos: [{ key: "fieldset-basic", title: "Contactgegevens", description: "Met kader, uitleg en een rij velden naast elkaar.", align: "block" }],
    props: ["FieldsetProps"],
    notes: [
      "Gebruikt het echte fieldset-element, dus disabled zet in één keer alles erin uit — ook velden van derden.",
      "Met row staan de velden naast elkaar; ze vouwen vanzelf om op smalle schermen.",
    ],
  },
  {
    slug: "checkbox",
    name: "Checkbox",
    description: "Aanvinkvakje met derde staat en beschrijving.",
    category: "Formulieren",
    files: ["checkbox.tsx", "checkbox.css"],
    // checkbox.tsx importeert useFieldContext uit ./field.
    dependsOn: ["field"],
    demos: [{ key: "checkbox-basic", title: "Staten", align: "block" }],
    props: ["CheckboxProps"],
  },
  {
    slug: "radio-group",
    name: "RadioGroup",
    description: "Groep keuzerondjes, ook als klikbare kaarten.",
    category: "Formulieren",
    files: ["radio-group.tsx", "radio-group.css"],
    demos: [
      { key: "radio-basic", title: "Standaard", align: "block" },
      { key: "radio-cards", title: "Als kaarten", align: "block" },
    ],
    props: ["RadioGroupProps", "RadioProps"],
  },
  {
    slug: "rating",
    name: "Rating",
    description: "Sterren om iets te beoordelen of een score te tonen.",
    category: "Formulieren",
    files: ["rating.tsx", "rating.css"],
    demos: [{ key: "rating-basic", title: "Kiezen en tonen", description: "Halve sterren, alleen-lezen variant en bediening met het toetsenbord." }],
    props: ["RatingProps"],
    notes: [
      "Met half klik je op de linkerhelft van een ster voor een halve punt.",
      "readOnly maakt er een weergave van: de rol wordt img in plaats van slider.",
    ],
  },
  {
    slug: "switch",
    name: "Switch",
    description: "Aan/uit-schakelaar met label en beschrijving.",
    category: "Formulieren",
    files: ["switch.tsx", "switch.css"],
    demos: [{ key: "switch-basic", title: "Varianten", align: "block" }],
    props: ["SwitchProps"],
  },
  {
    slug: "toggle",
    name: "Toggle",
    description: "Knop die ingedrukt blijft staan, los of in een groep.",
    category: "Formulieren",
    files: ["toggle.tsx", "toggle.css"],
    demos: [{ key: "toggle-basic", title: "Los, meervoudig en enkelvoudig", description: "Toggle, ToggleGroup met type multiple, en een aaneengesloten groep." }],
    props: ["ToggleProps", "ToggleGroupProps", "ToggleGroupItemProps"],
    notes: [
      "Voor een aan/uit-instelling gebruik je Switch; Toggle is voor een knop die ingedrukt blijft, zoals vet in een werkbalk.",
      "ToggleGroup met type single lijkt op Segmented, maar hier mag ook niets gekozen zijn.",
    ],
  },
  {
    slug: "select",
    name: "Select",
    description: "Eigen keuzelijst — geen native select, volledig stijlbaar.",
    category: "Formulieren",
    files: ["select.tsx", "select.css"],
    demos: [
      { key: "select-basic", title: "Standaard", align: "block" },
      { key: "select-rich", title: "Met groepen, iconen en zoeken", align: "block" },
    ],
    props: ["SelectProps", "SelectItemProps", "SelectContentProps"],
  },
  {
    slug: "alert",
    name: "Alert",
    description: "Inline melding met toon, titel en actie.",
    category: "Feedback",
    files: ["alert.tsx", "alert.css"],
    demos: [{ key: "alert-basic", title: "Tonen", align: "block" }],
    props: ["AlertProps"],
  },
  {
    slug: "empty-state",
    name: "EmptyState",
    description: "Lege lijst, geen resultaten of nog niets ingesteld.",
    category: "Feedback",
    files: ["empty-state.tsx", "empty-state.css"],
    demos: [{ key: "empty-basic", title: "Standaard", align: "block" }],
    props: ["EmptyStateProps"],
  },
  {
    slug: "indicator",
    name: "Indicator",
    description: "Telbadge of stip op de hoek van een knop, avatar of tab.",
    category: "Feedback",
    files: ["indicator.tsx", "indicator.css"],
    demos: [{ key: "indicator-basic", title: "Tellers en stippen", description: "Met max voor 99+, een stip, en verborgen bij nul." }],
    props: ["IndicatorProps"],
    notes: [
      "Zonder label is het hoekje aria-hidden: het getal hoort dan ook in de knoptekst te staan, anders hoort een schermlezer het niet.",
      "hidden laat het element staan maar toont niets — handig bij nul meldingen.",
    ],
  },
  {
    slug: "progress",
    name: "Progress",
    description: "Voortgangsbalk en ronde variant, ook onbepaald.",
    category: "Data",
    files: ["progress.tsx", "progress.css"],
    demos: [{ key: "progress-basic", title: "Balk en cirkel", align: "block" }],
    props: ["ProgressProps", "ProgressCircleProps"],
  },
  {
    slug: "tabs",
    name: "Tabs",
    description: "Tabbladen in drie stijlen, met pijltjesnavigatie.",
    category: "Navigatie",
    files: ["tabs.tsx", "tabs.css"],
    demos: [
      { key: "tabs-basic", title: "Line, pill en solid", align: "block" },
    ],
    props: ["TabsProps", "TabsTriggerProps"],
  },
  {
    slug: "segmented",
    name: "Segmented",
    description: "Compacte keuzeschakelaar voor weergaven en filters.",
    category: "Navigatie",
    files: ["segmented.tsx", "segmented.css"],
    demos: [{ key: "segmented-basic", title: "Varianten", align: "block" }],
    props: ["SegmentedProps", "SegmentedOption"],
  },
  {
    slug: "accordion",
    name: "Accordion",
    description: "In- en uitklapbare secties, enkel of meervoudig.",
    category: "Navigatie",
    files: ["accordion.tsx", "accordion.css"],
    demos: [{ key: "accordion-basic", title: "Varianten", align: "block" }],
    props: ["AccordionProps", "AccordionItemProps"],
  },
  {
    slug: "collapsible",
    name: "Collapsible",
    description: "Eén stuk inhoud dat open- en dichtklapt, met echte hoogte-animatie.",
    category: "Navigatie",
    files: ["collapsible.tsx", "collapsible.css"],
    demos: [{ key: "collapsible-basic", title: "Eerdere afspraken", description: "De hoogte groeit mee met de inhoud, zonder die te meten.", align: "block" }],
    props: ["CollapsibleProps", "CollapsibleTriggerProps", "CollapsibleContentProps"],
    notes: [
      "Gebruik Accordion als er meerdere secties zijn die elkaar afwisselen; Collapsible is voor één blok.",
      "De animatie werkt met grid-template-rows van 0fr naar 1fr, dus ook inhoud die onderweg verandert schuift netjes mee.",
    ],
  },
  {
    slug: "menubar",
    name: "Menubar",
    description: "Vaste menubalk zoals in een desktop-app: Dossier, Bewerken, Beeld.",
    category: "Navigatie",
    files: ["menubar.tsx", "menubar.css"],
    dependsOn: ["dropdown-menu"],
    demos: [{ key: "menubar-basic", title: "Drie menu's", description: "Eenmaal open volgen de andere menu's je muis, zoals in een echte menubalk." }],
    props: ["MenubarProps", "MenubarMenuProps", "MenubarTriggerProps"],
    notes: [
      "Gebruikt dezelfde items als DropdownMenu: DropdownMenuItem, -Label, -Separator en -Group werken hierbinnen.",
      "Bedoeld voor schermen met een muis; op mobiel is een DropdownMenu of Drawer een betere keuze.",
    ],
  },
  {
    slug: "breadcrumb",
    name: "Breadcrumb",
    description: "Kruimelpad met scheidingstekens.",
    category: "Navigatie",
    files: ["breadcrumb.tsx", "breadcrumb.css"],
    demos: [{ key: "breadcrumb-basic", title: "Standaard", align: "block" }],
    props: ["BreadcrumbProps", "BreadcrumbItemProps"],
  },
  {
    slug: "pagination",
    name: "Pagination",
    description: "Paginanavigatie met ellipsis en samenvatting.",
    category: "Navigatie",
    files: ["pagination.tsx", "pagination.css"],
    demos: [{ key: "pagination-basic", title: "Standaard", align: "block" }],
    props: ["PaginationProps"],
  },
  {
    slug: "stepper",
    name: "Stepper",
    description: "Voortgang door een meerstapsflow.",
    category: "Navigatie",
    files: ["stepper.tsx", "stepper.css"],
    demos: [{ key: "stepper-basic", title: "Horizontaal en verticaal", align: "block" }],
    props: ["StepperProps"],
  },
  {
    slug: "table",
    name: "Table",
    description: "Datatabel met sorteerbare koppen, dichte modus en toolbar.",
    category: "Data",
    files: ["table.tsx", "table.css"],
    demos: [{ key: "table-basic", title: "Sorteerbare tabel", align: "block" }],
    props: ["TableProps", "TableHeadProps", "TableRowProps"],
    notes: [
      "striped geeft om de andere rij een lichte achtergrond; stickyHeader laat de kop staan zodra je maxHeight meegeeft.",
      "Een selectiekolom maak je met een gewone Checkbox in de eerste cel — zo blijft de logica bij jou.",
    ],
  },
  {
    slug: "dialog",
    name: "Dialog",
    description: "Modaal venster met focus-trap, Escape en overlay.",
    category: "Overlays",
    files: ["dialog.tsx", "dialog.css"],
    dependsOn: ["button"],
    demos: [
      { key: "dialog-basic", title: "Standaard" },
      { key: "dialog-form", title: "Met formulier" },
    ],
    props: ["DialogProps", "DialogContentProps"],
  },
  {
    slug: "alert-dialog",
    name: "AlertDialog",
    description: "Bevestiging voor een actie die je niet zomaar terugdraait.",
    category: "Overlays",
    files: ["alert-dialog.tsx", "alert-dialog.css"],
    dependsOn: ["dialog", "button"],
    demos: [{ key: "alertdialog-basic", title: "Verwijderen bevestigen", description: "Twee manieren: de dialoog zelf plaatsen, of useConfirm() als belofte." }],
    props: ["AlertDialogProps"],
    notes: [
      "Anders dan Dialog: geen kruisje, klikken naast de dialoog sluit niet en de focus staat op Annuleren.",
      "Geeft onConfirm een belofte terug, dan blijft de knop laden tot ze klaar is en sluit de dialoog daarna.",
      "useConfirm() heeft een ConfirmProvider bovenaan je app nodig.",
    ],
  },
  {
    slug: "drawer",
    name: "Drawer",
    description: "Paneel dat vanaf een zijkant inschuift.",
    category: "Overlays",
    files: ["drawer.tsx", "drawer.css"],
    dependsOn: ["dialog", "button"],
    demos: [{ key: "drawer-basic", title: "Vier richtingen" }],
    props: ["DrawerProps", "DrawerContentProps"],
  },
  {
    slug: "popover",
    name: "Popover",
    description: "Zwevend paneel dat automatisch flipt bij weinig ruimte.",
    category: "Overlays",
    files: ["popover.tsx", "popover.css"],
    demos: [{ key: "popover-basic", title: "Standaard" }],
    props: ["PopoverProps", "PopoverContentProps"],
  },
  {
    slug: "hover-card",
    name: "HoverCard",
    description: "Kaartje met extra context bij hoveren, groter dan een tooltip.",
    category: "Overlays",
    files: ["hover-card.tsx", "hover-card.css"],
    demos: [{ key: "hovercard-basic", title: "Patiënt in een zin", description: "Hover over de naam; de kaart blijft open terwijl je ernaartoe beweegt." }],
    props: ["HoverCardProps", "HoverCardContentProps"],
    notes: [
      "Alleen voor aanvullende informatie: op touch bestaat hoveren niet, en de kaart opent daar dus nooit.",
      "Toetsenbordgebruikers krijgen de kaart bij focus op de trigger.",
    ],
  },
  {
    slug: "tooltip",
    name: "Tooltip",
    description: "Korte uitleg bij hover én toetsenbordfocus.",
    category: "Overlays",
    files: ["tooltip.tsx", "tooltip.css"],
    demos: [{ key: "tooltip-basic", title: "Vier zijden" }],
    props: ["TooltipProps"],
  },
  {
    slug: "dropdown-menu",
    name: "DropdownMenu",
    description: "Actiemenu met pijltjesnavigatie, sneltoetsen en secties.",
    category: "Overlays",
    files: ["dropdown-menu.tsx", "dropdown-menu.css"],
    dependsOn: ["button"],
    demos: [{ key: "dropdown-basic", title: "Menu met secties" }],
    props: ["DropdownMenuProps", "DropdownMenuItemProps"],
  },
  {
    slug: "context-menu",
    name: "ContextMenu",
    description: "Menu op de rechtermuisknop, op de plek van de cursor.",
    category: "Overlays",
    files: ["context-menu.tsx", "context-menu.css"],
    dependsOn: ["dropdown-menu"],
    demos: [{ key: "contextmenu-basic", title: "Rechtermuisklik", description: "Dezelfde items als DropdownMenu, inclusief toetsenbordnavigatie." }],
    props: ["ContextMenuProps", "ContextMenuTriggerProps"],
    notes: [
      "Gebruikt dezelfde items als DropdownMenu: DropdownMenuItem, -Label, -Separator en -Group werken hierbinnen.",
      "Op touch bestaat rechtsklikken niet; zorg dat elke actie ook ergens anders bereikbaar is.",
    ],
  },
  {
    slug: "toast",
    name: "Toast",
    description: "Tijdelijke melding met toon, actie en automatische sluiting.",
    category: "Overlays",
    files: ["toast.tsx", "toast.css"],
    demos: [{ key: "toast-basic", title: "Tonen" }],
    props: ["ToastOptions", "ToastProviderProps"],
    notes: ["Zet ToastProvider één keer rond je app; daarna roep je overal useToast() aan."],
  },
  {
    slug: "command",
    name: "Command",
    description: "Zoek- en actiepalet met ⌘K-sneltoets.",
    category: "Overlays",
    files: ["command.tsx", "command.css"],
    dependsOn: ["dialog"],
    demos: [{ key: "command-basic", title: "Palet", align: "block" }],
    props: ["CommandProps", "CommandItemProps", "CommandDialogProps"],
  },
  {
    slug: "combobox",
    name: "Combobox",
    description: "Zoekbare keuzelijst met toetsenbordnavigatie.",
    category: "Formulieren",
    files: ["combobox.tsx", "combobox.css"],
    dependsOn: ["select"],
    demos: [{ key: "combobox-basic", title: "Zoeken en kiezen", align: "block" }],
    props: ["ComboboxProps", "ComboboxOption"],
  },
  {
    slug: "modal-manager",
    name: "ModalProvider",
    description: "Dialogs imperatief openen vanuit één register, met useModal().",
    category: "Overlays",
    files: ["modal-manager.tsx"],
    dependsOn: ["dialog"],
    demos: [{ key: "modal-manager-basic", title: "Register en useModal()", align: "block" }],
    props: ["ModalProviderProps", "ModalApi"],
    notes: [
      "Handig zodra je veel dialogs vanuit menu's, tabellen of een store opent. De declaratieve Dialog blijft gewoon werken — dit is een extra laag, geen vervanging.",
      "Elk geregistreerd component krijgt zijn eigen props plus onClose en rendert zelf een Dialog of Drawer. Met createModals() weet TypeScript welke props bij welke soort horen.",
    ],
  },
  {
    slug: "calendar",
    name: "Calendar",
    description: "Maandkalender met enkelvoudige, bereik- en meervoudige selectie.",
    category: "Datum & planning",
    files: ["calendar.tsx", "calendar.css", "../lib/date.ts"],
    demos: [
      { key: "calendar-basic", title: "Eén datum en een periode", align: "block" },
      { key: "calendar-multiple", title: "Meerdere dagen", align: "block" },
    ],
    props: ["CalendarBaseProps", "CalendarSingleProps", "CalendarRangeProps", "CalendarMultipleProps"],
    notes: [
      "Toetsenbord: pijltjes verplaatsen per dag of week, Home en End springen naar het begin of einde van de week, PageUp en PageDown wisselen van maand (met Shift van jaar).",
      "De datumhulpfuncties in lib/date.ts worden meegekopieerd en zijn ook los bruikbaar: startOfWeek, getISOWeek, formatDateRange, parseTime en meer.",
    ],
  },
  {
    slug: "date-picker",
    name: "DatePicker",
    description: "Datum of periode kiezen in een popover, met snelkeuzes.",
    category: "Datum & planning",
    files: ["date-picker.tsx", "date-picker.css"],
    dependsOn: ["calendar", "popover", "field"],
    demos: [{ key: "datepicker-basic", title: "Datum en periode", align: "block" }],
    props: ["DatePickerProps", "DateRangePickerProps"],
  },
  {
    slug: "time-field",
    name: "TimeField",
    description: "Tijd invoeren met slimme parsing, stappen en tijdslotsuggesties.",
    category: "Datum & planning",
    files: ["time-field.tsx", "time-field.css", "../lib/date.ts"],
    dependsOn: ["field"],
    demos: [{ key: "timefield-basic", title: "Tijd en tijdsduur", align: "block" }],
    props: ["TimeFieldProps", "TimeRangeFieldProps"],
    notes: [
      "Het veld begrijpt 9, 930, 9.30 en 09:30 en formatteert bij het verlaten van het veld. Pijltjes omhoog en omlaag springen per stap.",
    ],
  },
  {
    slug: "period-nav",
    name: "PeriodNav",
    description: "Vorige en volgende door weken, maanden of elke andere periode.",
    category: "Datum & planning",
    files: ["period-nav.tsx", "period-nav.css"],
    demos: [{ key: "periodnav-basic", title: "Weken doorlopen", align: "block" }],
    props: ["PeriodNavProps"],
  },
  {
    slug: "week-schedule",
    name: "WeekSchedule",
    description: "Weekplanning met uurraster, overlappende blokken en drag & drop.",
    category: "Datum & planning",
    files: ["week-schedule.tsx", "week-schedule.css", "../lib/date.ts"],
    demos: [
      { key: "schedule-basic", title: "Rooster met verslepen", align: "block" },
      { key: "agenda-views", title: "Vier weergaven, één datamodel", description: "Dezelfde resources en events in ResourceColumns, WeekSchedule, TimeSlotList en Swimlanes.", align: "block" },
    ],
    props: ["WeekScheduleProps", "ScheduleEvent", "ScheduleResource"],
    notes: [
      "Slepen, verkleinen en verlengen zijn zelf geschreven met pointer events — geen dnd-kit of react-beautiful-dnd.",
      "Overlappende diensten worden automatisch naast elkaar gelegd; blokken met locked blijven staan.",
    ],
  },
  {
    slug: "resource-columns",
    name: "ResourceColumns",
    description: "Dagagenda met een kolom per arts, kamer of medewerker.",
    category: "Datum & planning",
    files: ["resource-columns.tsx", "resource-columns.css", "../lib/schedule.ts"],
    demos: [{ key: "resource-columns-basic", title: "Kolommen, met inklappen", align: "block" }],
    props: ["ResourceColumnsProps"],
    notes: [
      "Met collapseEmpty krimpen kolommen zonder afspraken tot een smalle rail, zodat de drukke kolommen alle ruimte krijgen.",
    ],
  },
  {
    slug: "swimlanes",
    name: "Swimlanes",
    description: "De agenda op zijn kant: een baan per resource, tijd van links naar rechts.",
    category: "Datum & planning",
    files: ["swimlanes.tsx", "swimlanes.css", "../lib/schedule.ts"],
    demos: [{ key: "swimlanes-basic", title: "Kamers en zalen", align: "block" }],
    props: ["SwimlanesProps"],
    notes: [
      "Gaten en overlappingen tussen mensen of ruimtes vallen hier het snelst op. De namenkolom blijft links staan tijdens het horizontaal scrollen.",
    ],
  },
  {
    slug: "time-slot-list",
    name: "TimeSlotList",
    description: "De dag als verticale tijdlijn, met kaartjes per tijdstip.",
    category: "Datum & planning",
    files: ["time-slot-list.tsx", "time-slot-list.css", "../lib/schedule.ts"],
    demos: [{ key: "timeslot-basic", title: "Dagoverzicht", align: "block" }],
    props: ["TimeSlotListProps"],
    notes: ["Werkt goed op smalle schermen: de kaartjes vullen automatisch de beschikbare breedte."],
  },
  {
    slug: "stat",
    name: "Stat",
    description: "KPI-tegel met waarde, icoon, trend en grafiekje.",
    category: "Data",
    files: ["stat.tsx", "stat.css"],
    dependsOn: ["chart"],
    demos: [{ key: "stat-basic", title: "KPI-raster", align: "block" }],
    props: ["StatProps"],
  },
  {
    slug: "data-pill",
    name: "DataPill",
    description: "Compacte meetwaarde: label, waarde en eenheid op één regel.",
    category: "Data",
    files: ["data-pill.tsx", "data-pill.css"],
    demos: [{ key: "datapill-basic", title: "Metingen en kerngegevens", align: "block" }],
    props: ["DataPillProps"],
  },
  {
    slug: "list-row",
    name: "ListRow",
    description: "Rij in een lijst: afspraak, document, gebruiker of melding.",
    category: "Data",
    files: ["list-row.tsx", "list-row.css"],
    demos: [{ key: "list-row-basic", title: "Agenda en documenten", align: "block" }],
    props: ["ListRowProps", "RowListProps", "RowIconProps"],
    notes: [
      "Alles behalve de titel is optioneel: lead, leading, subtitle, trailing en actions. Daardoor past dezelfde rij in een agenda, een documentenlijst of een meldingenpaneel.",
      "RowList bepaalt de vorm: bordered geeft één kaart met scheidingslijnen, separated losse kaartjes.",
    ],
  },
  {
    slug: "task-item",
    name: "TaskItem",
    description: "Eén taak in een lijst: afvinken, prioriteit, labels en deeltaken.",
    category: "Data",
    files: ["task-item.tsx", "task-item.css"],
    dependsOn: ["confetti"],
    demos: [{ key: "task-basic", title: "Takenlijst", description: "Met Composer om iets toe te voegen.", align: "block" }],
    props: ["TaskItemProps", "TaskListProps"],
    notes: [
      "Afvinken laat confetti uit de knop springen. Zet celebrate={false} als je dat liever niet hebt.",
      "Verwijderen schuift de rij eerst weg en roept daarna pas onDelete aan, zodat je lijst niet plots verspringt.",
    ],
  },
  {
    slug: "chart",
    name: "Charts",
    description: "Sparkline, staaf-, lijn- en donutgrafiek — eigen SVG, geen bibliotheek.",
    category: "Data",
    files: ["chart.tsx", "chart.css"],
    demos: [
      { key: "chart-bar", title: "Staaf en lijn", align: "block" },
      { key: "chart-donut", title: "Donut en sparkline", align: "block" },
    ],
    props: ["BarChartProps", "LineChartProps", "DonutChartProps", "SparklineProps"],
  },
  {
    slug: "area-chart",
    name: "AreaChart",
    description: "Gevuld vlak per reeks, met assen, hulplijnen en tooltip.",
    category: "Data",
    files: ["area-chart.tsx"],
    dependsOn: ["chart"],
    demos: [{ key: "areachart-basic", title: "Over elkaar en gestapeld", align: "block" }],
    props: ["AreaChartProps"],
    notes: [
      "De breedte wordt gemeten met een ResizeObserver, dus tekst en lijnen worden nooit uitgerekt.",
      "stacked telt de reeksen op; de as schaalt dan mee met het totaal in plaats van met de hoogste reeks.",
      "De tooltip volgt de dichtstbijzijnde kolom, niet het exacte punt — zo blijft hij bruikbaar op een dichte grafiek.",
    ],
  },
  {
    slug: "combo-chart",
    name: "ComboChart",
    description: "Staven en lijnen in één beeld, elk met een eigen as.",
    category: "Data",
    files: ["combo-chart.tsx"],
    dependsOn: ["chart"],
    demos: [{ key: "combochart-basic", title: "Omzet met marge", align: "block" }],
    props: ["ComboChartProps"],
    notes: [
      "Standaard krijgen de lijnen een tweede as rechts; met sharedAxis rekenen ze mee op de linkeras.",
      "stackedBars stapelt de staven per kolom in plaats van ze naast elkaar te zetten.",
    ],
  },
  {
    slug: "scatter-chart",
    name: "ScatterChart",
    description: "Punten op twee doorlopende assen, met optionele bubbelgrootte.",
    category: "Data",
    files: ["scatter-chart.tsx"],
    dependsOn: ["chart"],
    demos: [{ key: "scatterchart-basic", title: "Bezoeken tegen conversie", align: "block" }],
    props: ["ScatterChartProps", "ScatterSeries", "ScatterPoint"],
    notes: [
      "size op een punt maakt er een bubbelgrafiek van; de oppervlakte schaalt mee, niet de straal.",
      "Elk punt heeft ook een <title>, dus de waarde blijft leesbaar zonder JavaScript-tooltip.",
    ],
  },
  {
    slug: "bar-list",
    name: "BarList",
    description: "Rangschikking als horizontale balken met het label erin.",
    category: "Data",
    files: ["bar-list.tsx", "bar-list.css"],
    demos: [{ key: "barlist-basic", title: "Top pagina's en bronnen", align: "block" }],
    props: ["BarListProps", "BarListItem"],
    notes: [
      "Sorteert standaard aflopend; met limit toon je alleen de kop van de lijst.",
      "Een rij met href wordt een link, een rij met onSelect een knop — beide met focusring.",
    ],
  },
  {
    slug: "category-bar",
    name: "CategoryBar",
    description: "Eén balk in gekleurde stukken, met een wijzer op een waarde.",
    category: "Data",
    files: ["category-bar.tsx", "category-bar.css"],
    demos: [{ key: "categorybar-basic", title: "Verdeling met wijzer", align: "block" }],
    props: ["CategoryBarProps", "CategoryBarSegment"],
    notes: [
      "Segmenten mogen gewone getallen zijn; de verhouding wordt zelf berekend.",
      "marker rekent tegen hetzelfde totaal, dus je geeft er een absolute waarde in, geen percentage.",
    ],
  },
  {
    slug: "tracker",
    name: "Tracker",
    description: "Eén blokje per periode, gekleurd naar status — de uptimestrook.",
    category: "Data",
    files: ["tracker.tsx", "tracker.css"],
    dependsOn: ["visually-hidden"],
    demos: [{ key: "tracker-basic", title: "Beschikbaarheid per dag", align: "block" }],
    props: ["TrackerProps", "TrackerBlock"],
    notes: [
      "De blokjes vullen de breedte samen op; bij veel dagen worden ze smaller in plaats van te scrollen.",
      "label per blok gaat naar schermlezers, tooltip alleen naar de muis.",
    ],
  },
  {
    slug: "contribution-graph",
    name: "ContributionGraph",
    description: "Kalenderraster met één vakje per dag, donkerder bij meer activiteit.",
    category: "Data",
    files: ["contribution-graph.tsx", "contribution-graph.css"],
    demos: [{ key: "contributiongraph-basic", title: "Een jaar activiteit", align: "block" }],
    props: ["ContributionGraphProps", "ContributionDay"],
    notes: [
      "Zonder thresholds worden de vier stappen afgeleid uit de kwartielen van je eigen data.",
      "Dagen na `until` blijven leeg, zodat de laatste week niet halverwege afbreekt.",
      "Maandnamen en weekdagen komen uit Intl, dus ze volgen de locale die je meegeeft.",
    ],
  },
  {
    slug: "gauge",
    name: "Gauge",
    description: "Boog met één waarde in het midden en drempelkleuren.",
    category: "Data",
    files: ["gauge.tsx", "gauge.css"],
    demos: [{ key: "gauge-basic", title: "Drie meters", align: "block" }],
    props: ["GaugeProps", "GaugeThreshold"],
    notes: [
      "sweep bepaalt hoeveel graden de boog beslaat: 180 is een halve cirkel, 220 de klassieke meter.",
      "Dezelfde drempellogica als Meter, zodat een dashboard met beide er consistent uitziet.",
    ],
  },
  {
    slug: "radar-chart",
    name: "RadarChart",
    description: "Spinnenweb waarin elke reeks een veelhoek over de assen vormt.",
    category: "Data",
    files: ["radar-chart.tsx"],
    dependsOn: ["chart"],
    demos: [{ key: "radarchart-basic", title: "Profielen vergelijken", align: "block" }],
    props: ["RadarChartProps"],
    notes: [
      "Minstens drie assen; met minder valt er geen vlak te tekenen en toont het component de lege staat.",
      "De bovengrens komt uit niceScale, of geef max mee om meerdere grafieken gelijk te schalen.",
    ],
  },
  {
    slug: "data-table",
    name: "DataTable",
    description: "Tabel met sorteren, zoeken, selecteren en paginering in één component.",
    category: "Data",
    files: ["data-table.tsx", "data-table.css"],
    dependsOn: ["table", "checkbox", "input", "pagination", "skeleton", "empty-state"],
    demos: [{ key: "datatable-basic", title: "Klantenlijst", align: "block" }],
    props: ["DataTableProps", "DataTableColumn", "DataTableSort"],
    notes: [
      "Alles werkt uncontrolled: geef alleen data en columns mee en je hebt sorteren, zoeken en bladeren.",
      "Met manual doet het component geen filter- of sorteerwerk meer; dan toon je gewoon de bladzijde die de server teruggaf en gebruik je total voor het aantal pagina's.",
      "Een derde klik op een kolomkop zet het sorteren weer uit, zodat de oorspronkelijke volgorde terugkomt.",
      "hideBelow verbergt een kolom onder 640, 860 of 1024 pixels, zodat de tabel op een telefoon niet hoeft te scrollen.",
    ],
  },
  {
    slug: "form",
    name: "Form",
    description: "Formulierstatus, validatieregels en foutmeldingen zonder externe library.",
    category: "Formulieren",
    files: ["form.tsx", "form.css"],
    dependsOn: ["field"],
    demos: [{ key: "form-basic", title: "Contactformulier met validatie", align: "block" }],
    props: ["UseFormOptions", "UseFormReturn", "FormProps", "FormFieldProps", "FormActionsProps"],
    notes: [
      "useForm houdt values, errors, touched en submitting bij; Form zet noValidate zodat jouw meldingen die van de browser zijn.",
      "rules bevat required, email, minLength, maxLength, pattern, min, max en matches — gewone functies, dus je schrijft er zelf bij.",
      "Standaard verschijnt een fout pas na blur, maar een veld dat al fout stond verbetert meteen mee terwijl je typt.",
      "Geeft onSubmit een promise terug, dan staat submitting vanzelf aan tot ze klaar is.",
    ],
  },
  {
    slug: "editable",
    name: "Editable",
    description: "Tekst die je ter plekke bewerkt, met Enter bevestigen en Escape annuleren.",
    category: "Formulieren",
    files: ["editable.tsx", "editable.css"],
    demos: [{ key: "editable-basic", title: "Titel en notitie", align: "block" }],
    props: ["EditableProps"],
    notes: [
      "Enter bevestigt, Escape zet de oude waarde terug; met multiline bevestig je met Cmd of Ctrl + Enter.",
      "onSubmit mag async zijn en false teruggeven om het veld open te houden, bijvoorbeeld als de server de waarde weigert.",
      "submitOnBlur staat aan; zet hem uit en toon showActions wanneer per ongeluk wegklikken niet mag opslaan.",
    ],
  },
  {
    slug: "kanban",
    name: "Kanban",
    description: "Kolommen met kaarten die je sleept of met de pijltjes verplaatst.",
    category: "Data",
    files: ["kanban.tsx", "kanban.css"],
    demos: [{ key: "kanban-basic", title: "Sprintbord", align: "block" }],
    props: ["KanbanProps", "KanbanColumn", "KanbanCard", "KanbanMove"],
    notes: [
      "Zonder `cards` beheert het bord zijn eigen indeling; geef `cards` en `onCardsChange` mee zodra je de volgorde zelf wil bewaren.",
      "Slepen gaat met de HTML5 drag-and-drop van de browser, dus zonder library; een kaart met focus verhuist ook met pijltje links en rechts.",
      "limit kleurt de teller rood zodra er te veel kaarten in een kolom staan; locked weigert kaarten helemaal.",
    ],
  },
  {
    slug: "lightbox",
    name: "Lightbox",
    description: "Afbeeldingen schermvullend bekijken, met bladeren, miniaturen en zoom.",
    category: "Overlays",
    files: ["lightbox.tsx", "lightbox.css"],
    demos: [{ key: "lightbox-basic", title: "Galerij", align: "block" }],
    props: ["LightboxProps", "LightboxItem"],
    notes: [
      "Escape sluit, pijltjes bladeren, 0 zet de zoom terug op 100%; de focus blijft binnen het venster.",
      "Bij een zoom groter dan 100% sleep je de afbeelding met de muis; dubbelklikken springt tussen 100% en 200%.",
      "Elke wissel begint weer op ware grootte, zodat je nooit ingezoomd op een volgende foto belandt.",
    ],
  },
  {
    slug: "image-compare",
    name: "ImageCompare",
    description: "Twee afbeeldingen over elkaar met een schuif ertussen.",
    category: "Data",
    files: ["image-compare.tsx", "image-compare.css"],
    demos: [{ key: "imagecompare-basic", title: "Voor en na", align: "block" }],
    props: ["ImageCompareProps"],
    notes: [
      "De greep is een echte slider met role en aria-valuenow, dus pijltjes, Home en End werken en een schermlezer leest de stand voor.",
      "Met vertical schuif je van boven naar beneden; hoverToMove laat de schuif meelopen met de muis zonder te klikken.",
    ],
  },
  {
    slug: "masonry",
    name: "Masonry",
    description: "Kolommen waarin kaarten van ongelijke hoogte in elkaar schuiven.",
    category: "Layout",
    files: ["masonry.tsx", "masonry.css"],
    demos: [{ key: "masonry-basic", title: "Kaarten in drie kolommen", align: "block" }],
    props: ["MasonryProps"],
    notes: [
      "Standaard via CSS-kolommen: geen JavaScript nodig, maar de leesvolgorde loopt van boven naar beneden per kolom.",
      "Met balanced verdeelt het component de kinderen zelf en meet het de breedte met een ResizeObserver; kies dat bij interactieve kaarten.",
      "columns mag een getal zijn of een object met breekpunten, bv. { 0: 1, 640: 2, 1024: 3 }.",
    ],
  },
  {
    slug: "tour",
    name: "Tour",
    description: "Rondleiding die stap voor stap een element uitlicht met een kaartje ernaast.",
    category: "Overlays",
    files: ["tour.tsx", "tour.css"],
    demos: [{ key: "tour-basic", title: "Drie stappen", align: "block" }],
    props: ["TourProps", "TourStep"],
    notes: [
      "Het gat in de overlay is één clip-path, geen vier panelen, en wordt opnieuw gemeten bij scrollen en formaatwijziging.",
      "Elke stap wijst met een CSS-selector naar zijn element; een stap zonder target toont het kaartje midden in beeld.",
      "Het kaartje gaat onder het element staan en wijkt naar boven uit als daar geen plaats is.",
    ],
  },
  {
    slug: "marquee",
    name: "Marquee",
    description: "Rij die eindeloos doorloopt, in pure CSS.",
    category: "Layout",
    files: ["marquee.tsx", "marquee.css"],
    demos: [{ key: "marquee-basic", title: "Logo's en sectoren", align: "block" }],
    props: ["MarqueeProps"],
    notes: [
      "De inhoud wordt herhaald en precies één rij plus de gap opgeschoven; daardoor is de lus naadloos zonder JavaScript.",
      "Geen dependency en geen werk per frame: het is één CSS-animatie, die vanzelf stilvalt bij prefers-reduced-motion.",
      "pauseOnHover staat aan, zodat je iets kan aanklikken zonder het te moeten najagen.",
    ],
  },
  {
    slug: "in-view",
    name: "InView",
    description: "Inhoud die binnenkomt zodra ze in beeld scrolt, plus een leesbalk.",
    category: "Layout",
    files: ["in-view.tsx", "in-view.css"],
    demos: [{ key: "inview-basic", title: "Binnenkomen en voortgang", align: "block" }],
    props: ["InViewProps", "UseInViewOptions", "ScrollProgressProps"],
    notes: [
      "Gebruikt een IntersectionObserver en een CSS-overgang, dus geen animatielibrary nodig.",
      "useInView geeft je de ref en de stand, zodat je er ook zelf iets mee kan doen.",
      "ScrollProgress meet met requestAnimationFrame en kan binnen een scrollend paneel werken via target.",
    ],
  },
  {
    slug: "prompt-input",
    name: "PromptInput",
    description: "Invoerveld voor een gesprek met een model: groeit mee, bijlagen, stopknop.",
    category: "AI",
    files: ["prompt-input.tsx", "prompt-input.css"],
    demos: [{ key: "promptinput-basic", title: "Vraag stellen", align: "block" }],
    props: ["PromptInputProps", "PromptAttachment"],
    notes: [
      "Enter verstuurt, Shift+Enter maakt een regel; tijdens het antwoorden wordt de knop een stopknop.",
      "Het veld groeit mee tot maxRows en krimpt weer, doordat de hoogte eerst op auto gaat voor het meten.",
      "isComposing wordt gerespecteerd, zodat Enter tijdens het typen met een IME geen halve zin verstuurt.",
    ],
  },
  {
    slug: "streaming-text",
    name: "StreamingText",
    description: "Tekst die binnenkomt terwijl je kijkt, met een redeneerblok erbij.",
    category: "AI",
    files: ["streaming-text.tsx", "streaming-text.css"],
    demos: [{ key: "streamingtext-basic", title: "Antwoord en redenering", align: "block" }],
    props: ["StreamingTextProps", "ThinkingProps"],
    notes: [
      "Groeit de text aan, zoals bij een echte stream, dan loopt hij door; wordt hij vervangen, dan begint hij opnieuw.",
      "byWord onthult per woord in plaats van per teken — rustiger om te lezen bij lange antwoorden.",
      "Thinking glinstert zolang active aanstaat en toont daarna hoe lang het duurde; de redenering blijft ingeklapt.",
    ],
  },
  {
    slug: "tool-call",
    name: "ToolCall",
    description: "Welk gereedschap een model aanriep, met invoer, resultaat en een goedkeuringskaart.",
    category: "AI",
    files: ["tool-call.tsx", "tool-call.css"],
    demos: [{ key: "toolcall-basic", title: "Aanroepen en toestemming", align: "block" }],
    props: ["ToolCallProps", "ApprovalCardProps"],
    notes: [
      "Dichtgeklapt is het één regel met de naam, een samenvatting en de duur; open zie je invoer en resultaat als JSON.",
      "Objecten worden zelf naar JSON gezet, strings blijven zoals ze zijn.",
      "ApprovalCard toont de details vóór de knoppen, zodat duidelijk is waar je ja op zegt; met decision bevriest hij de uitkomst.",
    ],
  },
  {
    slug: "citations",
    name: "Citations",
    description: "Bronverwijzingen in de tekst met een lijst eronder, plus een verbruiksmeter.",
    category: "AI",
    files: ["citations.tsx", "citations.css"],
    demos: [{ key: "citations-basic", title: "Bronnen en quota", align: "block" }],
    props: ["CitationsProps", "CitationMarkProps", "Citation", "UsageQuotaProps"],
    notes: [
      "Het bolletje in de tekst en de rij in de lijst lichten samen op, in beide richtingen.",
      "Een bron met url wordt een echte link die in een nieuw tabblad opent; zonder url blijft het een sup-element.",
      "UsageQuota kleurt amber en rood via thresholds en toont wanneer de teller weer aanvult.",
    ],
  },
  {
    slug: "number-flow",
    name: "NumberFlow",
    description: "Getal dat naar zijn nieuwe waarde rolt in plaats van te verspringen.",
    category: "Motion",
    files: ["../motion/number-flow.tsx", "../motion/motion.css"],
    requires: ["motion"],
    demos: [{ key: "numberflow-basic", title: "Omzet en bezoekers", align: "block" }],
    props: ["NumberFlowProps"],
    notes: [
      "Elk cijfer rolt apart, dus alleen wat verandert beweegt; de richting bepaalt of het van boven of onder komt.",
      "Met roll={false} telt het hele getal op met een easeOutCubic in plaats van per cijfer te rollen.",
      "De volledige waarde staat in aria-label, zodat een schermlezer niet elk los cijfer voorleest.",
    ],
  },
  {
    slug: "dock",
    name: "Dock",
    description: "Rij iconen die opzwelt onder de muis, zoals de dock van macOS.",
    category: "Motion",
    files: ["../motion/dock.tsx", "../motion/motion.css"],
    requires: ["motion"],
    demos: [{ key: "dock-basic", title: "Zes iconen", align: "block" }],
    props: ["DockProps", "DockItemProps"],
    notes: [
      "De afstand tot de muis stuurt de grootte via een spring per item; distance bepaalt hoe breed het effect uitwaaiert.",
      "Met vertical staat de dock rechtop en meet hij de muis op de y-as.",
      "Bij prefers-reduced-motion blijven de iconen op hun rustige grootte staan.",
    ],
  },
  {
    slug: "animated-list",
    name: "AnimatedList",
    description: "Lijst waarin items binnenschuiven en weggaan zonder sprong.",
    category: "Motion",
    files: ["../motion/animated-list.tsx", "../motion/motion.css"],
    requires: ["motion"],
    demos: [{ key: "animatedlist-basic", title: "Binnenkomende meldingen", align: "block" }],
    props: ["AnimatedListProps", "AnimatedListItemProps"],
    notes: [
      "Elk kind heeft een stabiele key nodig; daarop herkent motion wat nieuw is en wat blijft.",
      "layout zorgt dat de rijen eronder meeschuiven in plaats van te verspringen.",
      "max knipt de lijst af, zodat een stroom meldingen niet eindeloos doorgroeit.",
    ],
  },
  {
    slug: "multi-step-loader",
    name: "MultiStepLoader",
    description: "Wachtscherm dat vertelt wát er gebeurt in plaats van alleen te draaien.",
    category: "Motion",
    files: ["../motion/multi-step-loader.tsx", "../motion/motion.css"],
    requires: ["motion"],
    demos: [{ key: "multisteploader-basic", title: "Importeren in vijf stappen", align: "block" }],
    props: ["MultiStepLoaderProps", "LoaderStep"],
    notes: [
      "Zonder step loopt hij op de klok; geef step mee zodra je echte voortgang hebt.",
      "Een losse stap mag een eigen duration hebben, voor het stuk dat altijd langer duurt.",
      "overlay legt het geheel over het scherm met een waas erachter.",
    ],
  },
  {
    slug: "swipe-to-delete",
    name: "SwipeToDelete",
    description: "Rij die je opzij veegt om hem te verwijderen, met een knop om het vast te houden.",
    category: "Motion",
    files: ["../motion/swipe-to-delete.tsx", "../motion/hold-to-confirm.tsx", "../motion/motion.css"],
    requires: ["motion"],
    demos: [{ key: "swipetodelete-basic", title: "Vegen en vasthouden", align: "block" }],
    props: ["SwipeToDeleteProps", "HoldToConfirmProps"],
    notes: [
      "Onder de drempel veert de rij terug; erboven glijdt ze weg en klapt de hoogte dicht, zodat de lijst niet springt.",
      "Met confirm blijft de rij open staan met een knop erachter, voor iets dat echt niet per ongeluk mag.",
      "HoldToConfirm vervangt de \"weet je het zeker\"-dialoog door een knop die je even vasthoudt; bij rustige beweging duurt dat maar kort.",
    ],
  },
  {
    slug: "phone-input",
    name: "PhoneInput",
    description: "Telefoonnummer met landkiezer; de waarde komt er als E.164 uit.",
    category: "Formulieren",
    files: ["phone-input.tsx", "phone-input.css"],
    dependsOn: ["field"],
    demos: [{ key: "phoneinput-basic", title: "Gsm en vaste lijn", align: "block" }],
    props: ["PhoneInputProps", "PhoneCountry"],
    notes: [
      "In het veld staat het nummer leesbaar gegroepeerd per land, maar onValueChange geeft altijd E.164 terug (+32470123456).",
      "Typ je zelf een + met landnummer, dan springt de kiezer mee; fromE164 en toE164 zijn los exporteerbaar.",
      "PHONE_COUNTRIES bevat de buurlanden en wat in België vaak voorkomt; geef je eigen lijst mee voor meer.",
      "De vlagemoji wordt uit de landcode berekend, dus er komt geen plaatjesset bij kijken.",
    ],
    isNew: true,
  },
  {
    slug: "cookie-consent",
    name: "CookieConsent",
    description: "Toestemmingsbalk met categorieën, zoals de GDPR ze verlangt.",
    category: "Overlays",
    files: ["cookie-consent.tsx", "cookie-consent.css"],
    dependsOn: ["switch"],
    demos: [{ key: "cookieconsent-basic", title: "Balk met instellingen", align: "block" }],
    props: ["CookieConsentProps", "CookieCategory"],
    notes: [
      "Weigeren staat even prominent als aanvaarden, en niets staat vooraf aan behalve wat als required gemarkeerd is.",
      "De keuze gaat naar localStorage met een datum erbij en verloopt na expiresInDays; readConsent leest ze elders terug.",
      "De balk verschijnt pas na het monteren, zodat hij niet flitst bij iemand die allang gekozen heeft.",
      "Werkt de opslag niet (privémodus), dan geldt de keuze gewoon voor dit bezoek — het component valt niet om.",
    ],
    isNew: true,
  },
  {
    slug: "signature",
    name: "Signature",
    description: "Vlak om met muis, vinger of pen een handtekening te zetten.",
    category: "Formulieren",
    files: ["signature.tsx", "signature.css"],
    demos: [{ key: "signature-basic", title: "Tekenen en vastleggen", align: "block" }],
    props: ["SignatureProps", "SignatureHandle"],
    notes: [
      "De lijn wordt gladgetrokken met een midpoint-curve, zodat een snelle haal niet hoekig wordt.",
      "Het canvas staat op devicePixelRatio, dus de lijn blijft scherp op een retina-scherm en bij resize.",
      "Via de ref krijg je clear, undo, isEmpty, toDataURL en toBlob — dat laatste om rechtstreeks te uploaden.",
    ],
    isNew: true,
  },
  {
    slug: "relative-time",
    name: "RelativeTime",
    description: "\"3 minuten geleden\", en vanaf een paar dagen gewoon de datum.",
    category: "Datum & planning",
    files: ["relative-time.tsx", "relative-time.css"],
    demos: [{ key: "relativetime-basic", title: "Momenten en leesrichting", align: "block" }],
    props: ["RelativeTimeProps"],
    notes: [
      "Rendert een echt <time>-element met het ISO-moment in dateTime, en de volledige datum in de tooltip.",
      "Werkt zichzelf bij zolang dat zinvol is: elke seconde onder de minuut, elke minuut onder het uur, daarna niet meer.",
      "Vanaf thresholdDays toont het component de datum zelf — \"37 dagen geleden\" zegt niemand iets.",
      "De prop heet format en niet style, omdat style op een DOM-element al bezet is.",
    ],
    isNew: true,
  },
  {
    slug: "direction",
    name: "DirectionProvider",
    description: "Zet de leesrichting voor alles eronder; de componenten spiegelen mee.",
    category: "Layout",
    files: ["direction.tsx", "direction.css"],
    demos: [{ key: "relativetime-basic", title: "Rechts naar links", align: "block" }],
    props: ["DirectionProviderProps"],
    notes: [
      "De componenten gebruiken logische CSS-eigenschappen (inset-inline, margin-inline, border-inline), dus met dir=\"rtl\" klopt alles vanzelf.",
      "De wikkel staat op display: contents, zodat een provider midden in een flex- of grid-container niets breekt.",
      "useDirection en useIsRtl lezen de richting uit, bijvoorbeeld om zelf een pijltje om te draaien.",
      "applyToDocument zet dir ook op <html>, nodig voor overlays die in een Portal buiten de wikkel hangen.",
    ],
    isNew: true,
  },
  {
    slug: "countdown",
    name: "Countdown",
    description: "Telt af naar een moment en stopt vanzelf op nul.",
    category: "Data",
    files: ["countdown.tsx", "countdown.css"],
    demos: [{ key: "countdown-basic", title: "Twee tellers", description: "Met labels, en compact met dubbele punten." }],
    props: ["CountdownProps"],
    notes: [
      "onComplete wordt precies één keer aangeroepen; daarna stopt de interval.",
      "Dagen verschijnen alleen zolang er meer dan 24 uur over is.",
    ],
  },
  {
    slug: "carousel",
    name: "Carousel",
    description: "Reeks kaarten of beelden met scroll-snap, knoppen en stippen.",
    category: "Data",
    files: ["carousel.tsx", "carousel.css"],
    dependsOn: ["button"],
    demos: [{ key: "carousel-basic", title: "Beelden bij een dossier", description: "Vegen, pijltjestoetsen of de knoppen; de browser doet het schuiven.", align: "block" }],
    props: ["CarouselProps", "CarouselItemProps"],
    notes: [
      "Het schuiven gebeurt met scroll-snap in plaats van met JavaScript: vegen op touch voelt daardoor natuurlijk aan.",
      "Met size per item toon je er meerdere tegelijk, bijvoorbeeld size=\"70%\" voor een glimp van de volgende.",
      "autoPlay staat standaard uit; zet het alleen aan als de inhoud niet belangrijk is om te lezen.",
    ],
  },
  {
    slug: "timeline",
    name: "Timeline",
    description: "Verticale lijn met gebeurtenissen: audit-log, dossierverloop, statuswissels.",
    category: "Data",
    files: ["timeline.tsx", "timeline.css"],
    demos: [{ key: "timeline-basic", title: "Verloop van een dossier", description: "Stippen met icoon, tijd, auteur en een onderbroken lijn voor wat nog komt.", align: "block" }],
    props: ["TimelineProps", "TimelineItemProps"],
    notes: ["Niet te verwarren met TimeSlotList: die toont een dag in uren, dit toont gebeurtenissen na elkaar."],
  },
  {
    slug: "message-thread",
    name: "MessageThread",
    description: "Verloop van een gesprek: ticket, interne notities of chat.",
    category: "Data",
    files: ["message-thread.tsx", "message-thread.css"],
    demos: [{ key: "messagethread-basic", title: "Ticketgesprek", description: "Met dagscheiding, systeemregel, interne notitie en de Composer eronder.", align: "block" }],
    props: ["MessageThreadProps", "MessageProps"],
    notes: [
      "Combineert met Composer voor de invoer eronder.",
      "Een bericht met internal krijgt een amber bel met het label \"Interne notitie\" — handig voor wat de klant niet ziet.",
    ],
  },
  {
    slug: "qr-code",
    name: "QrCode",
    description: "Echte, scanbare QR-code; zelf geschreven encoder zonder dependencies.",
    category: "Data",
    files: ["qr-code.tsx", "qr-encode.ts", "qr-code.css"],
    demos: [{ key: "qr-basic", title: "Live code", description: "Typ een andere waarde of kies een ander foutcorrectieniveau.", align: "block" }],
    props: ["QrCodeProps"],
    notes: [
      "Byte-modus, versie 1 tot en met 10: tot 271 tekens bij niveau M. Daarboven volgt een duidelijke foutmelding.",
      "De code blijft altijd zwart op wit, ook in donkere modus — scanners hebben dat contrast nodig.",
      "De stille zone van 4 modules zit standaard in de afbeelding; maak ze niet kleiner.",
    ],
  },
  {
    slug: "toolbar",
    name: "Toolbar",
    description: "Knoppenrij met groepen, scheidingslijnen en aan/uit-knoppen.",
    category: "Navigatie",
    files: ["toolbar.tsx", "toolbar.css"],
    demos: [{ key: "toolbar-basic", title: "Opmaak en acties", align: "block" }],
    props: ["ToolbarProps", "ToolbarButtonProps"],
  },
  {
    slug: "section-header",
    name: "SectionHeader",
    description: "Compacte kop boven een blok, met gekleurd staafje en acties.",
    category: "Layout",
    files: ["section-header.tsx", "section-header.css"],
    demos: [{ key: "section-header-basic", title: "Tonen en formaten", align: "block" }],
    props: ["SectionHeaderProps"],
  },
  {
    slug: "entity-header",
    name: "EntityHeader",
    description: "Kop van een dossier: media, naam, kerngegevens, labels en acties.",
    category: "Layout",
    files: ["entity-header.tsx", "entity-header.css"],
    demos: [{ key: "entity-header-basic", title: "Dossierkop met tabs", align: "block" }],
    props: ["EntityHeaderProps", "EntityDetail"],
  },
  {
    slug: "sidebar",
    name: "Sidebar",
    description: "Navigatiekolom met secties, badges en inklapstand.",
    category: "Navigatie",
    files: ["sidebar.tsx", "sidebar.css"],
    dependsOn: ["app-shell"],
    demos: [
      { key: "sidebar-basic", title: "In een app-shell", align: "block" },
      { key: "sidebar-inverted", title: "Donkere rail", description: "tone=\"inverted\" — kleuren afgeleid van het Lorenthi UI-accent, werkt in beide thema's.", align: "block" },
    ],
    props: ["SidebarProps", "SidebarItemProps"],
  },
  {
    slug: "bottom-nav",
    name: "BottomNav",
    description: "Vaste navigatiebalk onderaan op mobiel, met iconen, labels en tellers.",
    category: "Navigatie",
    files: ["bottom-nav.tsx", "bottom-nav.css"],
    demos: [{ key: "bottomnav-basic", title: "Vier bestemmingen", description: "Tik om te wisselen; de teller zit op het icoon." }],
    props: ["BottomNavProps", "BottomNavItemProps"],
    notes: [
      "Verschijnt onder 860px breed. Met always toon je hem altijd, bijvoorbeeld in een telefoonvoorbeeld.",
      "Geef je pagina onderaan evenveel padding als de hoogte van de balk, anders valt de laatste inhoud eronder.",
    ],
  },
  {
    slug: "fab",
    name: "Fab",
    description: "Zwevende hoofdactie, met SpeedDial voor een waaier aan acties.",
    category: "Navigatie",
    files: ["fab.tsx", "fab.css"],
    dependsOn: ["button"],
    demos: [{ key: "fab-basic", title: "Knop en waaier", description: "Links een gewone Fab, rechts een SpeedDial die openklapt.", align: "block" }],
    props: ["FabProps", "SpeedDialProps", "SpeedDialActionProps"],
    notes: [
      "Standaard hangt de knop vast rechtsonder, met ruimte voor de iOS-homebalk. Met position static zet je hem gewoon in de stroom.",
      "Een Fab hoort één actie te zijn; heb je er meer, gebruik dan SpeedDial.",
    ],
  },
  {
    slug: "app-shell",
    name: "AppShell",
    description: "Layout met vaste zijbalk, bovenbalk en inhoudskolom.",
    category: "Layout",
    files: ["app-shell.tsx", "app-shell.css"],
    demos: [{ key: "appshell-basic", title: "Volledige shell", align: "block" }],
    props: ["AppShellProps", "TopbarProps", "PageHeaderProps"],
  },
  {
    slug: "aspect-ratio",
    name: "AspectRatio",
    description: "Houdt een vaste verhouding aan, zodat niets verspringt tijdens het laden.",
    category: "Layout",
    files: ["aspect-ratio.tsx", "aspect-ratio.css"],
    demos: [{ key: "aspectratio-basic", title: "Drie verhoudingen", description: "16:9, 4:3 en vierkant." }],
    props: ["AspectRatioProps"],
    notes: ["Een img, video of iframe erin vult automatisch het vlak met object-fit cover."],
  },
  {
    slug: "workspace",
    name: "Workspace",
    description: "Werkblad met smalle rails links en rechts naast de inhoud.",
    category: "Layout",
    files: ["workspace.tsx", "workspace.css"],
    dependsOn: ["section-header"],
    demos: [{ key: "workspace-basic", title: "Drie kolommen", align: "block" }],
    props: ["WorkspaceProps", "WorkspaceRailProps"],
    notes: [
      "Het breekpunt (stackAt) kijkt naar de breedte van het werkblad zelf via een container query, niet naar het venster. Zo stapelt het ook correct wanneer het werkblad in een smalle kolom staat, en blijft het pure CSS: geen flits bij het laden, geen meting in JavaScript.",
    ],
  },
  {
    slug: "resizable",
    name: "ResizableGroup",
    description: "Panelen met een sleepbare scheiding ertussen.",
    category: "Layout",
    files: ["resizable.tsx", "resizable.css"],
    demos: [{ key: "resizable-basic", title: "Lijst en detail", description: "Sleep de scheiding, of gebruik de pijltjestoetsen (Shift voor stappen van 10%).", align: "block" }],
    props: ["ResizableGroupProps", "ResizablePanelProps", "ResizableHandleProps"],
    notes: [
      "Panelen en grepen krijgen een index mee, omdat ze in dezelfde rij door elkaar staan: greep index={0} verdeelt paneel 0 en 1.",
      "Maten zijn percentages, dus de verdeling blijft kloppen als het venster verandert.",
    ],
  },
  {
    slug: "scroll-area",
    name: "ScrollArea",
    description: "Scrollbaar vlak met een smalle balk en vervaging aan de randen.",
    category: "Layout",
    files: ["scroll-area.tsx", "scroll-area.css"],
    demos: [{ key: "scrollarea-basic", title: "Dagoverzicht", description: "De vervaging boven en onder verschijnt alleen als daar nog inhoud zit." }],
    props: ["ScrollAreaProps"],
    notes: [
      "Dit is de echte scrollbalk van de browser, alleen anders opgemaakt: vegen, scrollwiel en toetsenbord blijven werken zoals gebruikers gewend zijn.",
      "De vervaging gebruikt mask-image; zet fade uit als je inhoud met eigen maskers werkt.",
    ],
  },
  {
    slug: "mockup",
    name: "Mockup",
    description: "Een scherm in een browser-, venster- of telefoonframe zetten.",
    category: "Layout",
    files: ["mockup.tsx", "mockup.css"],
    demos: [{ key: "mockup-basic", title: "Drie frames", description: "MockupBrowser, MockupWindow en MockupPhone met echte inhoud erin.", align: "block" }],
    props: ["MockupBrowserProps", "MockupWindowProps", "MockupPhoneProps"],
    notes: [
      "Bedoeld voor documentatie, release-notes en marketingpagina's — niet voor de app zelf.",
      "MockupPhone schaalt op breedte; de hoogte volgt uit ratio (standaard 19,5:9).",
      "Met screen of wallpaper geef je het hele scherm een achtergrond; de statusbalk wordt dan vanzelf wit op donker. Zonder die props volgt het scherm het thema van de site.",
    ],
  },
  {
    slug: "auth-layout",
    name: "AuthLayout",
    description: "Aanmeldscherm: merkpaneel, kaart, scheiding en SSO-knoppen.",
    category: "Layout",
    files: ["auth-layout.tsx", "auth-layout.css"],
    demos: [
      { key: "auth-split", title: "Split met itsme® en eID", align: "block" },
      { key: "auth-centered", title: "Gecentreerd", align: "block" },
    ],
    props: ["AuthLayoutProps", "AuthCardProps", "AuthDividerProps", "SsoButtonProps"],
    notes: [
      "Het zijpaneel verdwijnt onder 900px, dus je hoeft geen apart mobiel scherm te bouwen.",
      "SsoButton neemt een merkkleur via color — die kleurt het icoonvlak, de rand bij hover en de pijl, zonder ergens een kleur hard te zetten.",
    ],
  },
  {
    slug: "confetti",
    name: "ConfettiBurst",
    description: "Kleine explosie van snippers bij iets dat af is.",
    category: "Feedback",
    files: ["confetti.tsx", "confetti.css"],
    demos: [{ key: "confetti-basic", title: "Vieren" }],
    props: ["ConfettiBurstProps"],
    notes: [
      "Rendert één keer en ruimt zichzelf op via onDone. Bij “verminderde beweging” gebeurt er niets.",
      "De kleuren komen standaard uit de thematokens, dus de confetti past zich aan licht en donker aan.",
    ],
  },
  {
    slug: "slider",
    name: "Slider",
    description: "Schuifregelaar met waardeweergave en tonen.",
    category: "Formulieren",
    files: ["slider.tsx", "slider.css"],
    demos: [{ key: "slider-basic", title: "Varianten", align: "block" }],
    props: ["SliderProps"],
  },
  {
    slug: "otp-input",
    name: "OtpInput",
    description: "Invoer van een verificatiecode, één teken per vakje.",
    category: "Formulieren",
    files: ["otp-input.tsx", "otp-input.css"],
    demos: [{ key: "otp-basic", title: "Zes cijfers", align: "block" }],
    props: ["OtpInputProps"],
  },
  {
    slug: "file-drop",
    name: "FileDrop",
    description: "Sleepzone voor bestanden, met bestandslijst.",
    category: "Formulieren",
    files: ["file-drop.tsx", "file-drop.css"],
    demos: [{ key: "filedrop-basic", title: "Uploadzone", align: "block" }],
    props: ["FileDropProps", "FileItemProps"],
  },
  {
    slug: "swatch-picker",
    name: "SwatchPicker",
    description: "Kleur kiezen uit een rij stalen, met optionele eigen kleur.",
    category: "Formulieren",
    files: ["swatch-picker.tsx", "swatch-picker.css"],
    demos: [{ key: "swatch-basic", title: "Stalen", align: "block" }],
    props: ["SwatchPickerProps"],
    notes: [
      "Elke geldige CSS-kleur mag, dus je kan er ook tokens in stoppen: var(--accent), var(--violet) …",
    ],
  },
  {
    slug: "avatar-upload",
    name: "AvatarUpload",
    description: "Profielfoto kiezen, bijsnijden en verkleinen in de browser.",
    category: "Formulieren",
    files: ["avatar-upload.tsx", "avatar-upload.css", "../lib/image.ts"],
    dependsOn: ["avatar"],
    demos: [{ key: "avatar-upload-basic", title: "Profiel bewerken", align: "block" }],
    props: ["AvatarUploadProps"],
    notes: [
      "De foto wordt vierkant bijgesneden en naar outputSize verkleind op een canvas. Je krijgt een compacte data-URL terug, klaar om te bewaren.",
    ],
  },
  {
    slug: "composer",
    name: "Composer",
    description: "Invoerbalk om snel iets toe te voegen, met microfoon en snelkeuzes.",
    category: "Formulieren",
    files: ["composer.tsx", "composer.css"],
    dependsOn: ["voice-button"],
    demos: [{ key: "composer-basic", title: "Toevoegen met snelkeuzes", align: "block" }],
    props: ["ComposerProps"],
    notes: [
      "Enter voegt toe en houdt de focus in het veld, zodat je meerdere regels na elkaar kan intypen.",
      "Kinderen van Composer komen onder het veld te staan — handig voor deadlines, lijsten of labels.",
    ],
  },
  {
    slug: "rich-editor",
    name: "RichEditor",
    description: "Tekstvak met opmaakknoppen: vet, cursief, markeren en lijsten.",
    category: "Formulieren",
    files: ["rich-editor.tsx", "rich-editor.css"],
    demos: [{ key: "richeditor-basic", title: "Verslag met opmaak", description: "Selecteer tekst en gebruik de werkbalk of Ctrl+B / Ctrl+I / Ctrl+U.", align: "block" }],
    props: ["RichEditorProps"],
    notes: [
      "De waarde is HTML. Komt ze van een gebruiker, saneer ze dan server-side voor je ze elders weer toont.",
      "Plakken gebeurt standaard als platte tekst, zodat opmaak uit Word of een webpagina niet meelift.",
      "Gebouwd op document.execCommand. Dat is als verouderd gemarkeerd, maar werkt in elke browser en heeft geen standaardopvolger.",
    ],
  },
  {
    slug: "voice-button",
    name: "VoiceButton",
    description: "Microfoonknop op de spraakherkenning van de browser.",
    category: "Formulieren",
    files: ["voice-button.tsx", "voice-button.css", "../lib/use-voice.ts"],
    demos: [{ key: "voice-basic", title: "Inspreken", description: "Werkt in Chrome en Edge; elders valt de knop netjes terug.", align: "block" }],
    props: ["VoiceButtonProps", "UseVoiceOptions"],
    notes: [
      "Spraakherkenning zit niet in elke browser. Met whenUnsupported kies je zelf of de knop verdwijnt, grijs wordt of gewoon blijft staan.",
      "useVoice geeft je hetzelfde zonder knop: { listening, supported, start, stop, toggle }.",
    ],
  },
  {
    slug: "pulse-dot",
    name: "PulseDot",
    description: "Statusbolletje met kloppende halo, voor live of bezet.",
    category: "Feedback",
    files: ["pulse-dot.tsx", "pulse-dot.css"],
    demos: [{ key: "pulsedot-basic", title: "Statussen", align: "block" }],
    props: ["PulseDotProps"],
  },
  {
    slug: "theme",
    name: "Theme",
    description: "Licht/donker met ThemeProvider, useTheme en ThemeToggle.",
    category: "Layout",
    files: ["theme.tsx", "theme.css"],
    demos: [
      { key: "theme-basic", title: "Schakelen", align: "block" },
      { key: "density-basic", title: "Dichtheid", description: "Compact, normaal of ruim — alle componenten schalen mee.", align: "block" },
    ],
    props: ["ThemeProviderProps", "ThemeToggleProps", "DensityToggleProps"],
    notes: [
      "Plaats ThemeScript in je head zodat het opgeslagen thema al vóór de eerste paint staat — geen witte flits bij het laden.",
      "De dichtheid staat in één token: --density. Elke hoogte en padding in de library is calc(Npx * var(--density)), dus compact en ruim werken meteen door in alle componenten.",
    ],
  },
  {
    slug: "motion-drawer",
    name: "MotionDrawerContent",
    description: "Drawer met veerbeweging, uitgaande animatie en wegvegen om te sluiten.",
    category: "Motion",
    files: ["../motion/motion-drawer.tsx", "../motion/motion.css"],
    dependsOn: ["drawer", "button"],
    requires: ["motion"],
    demos: [{ key: "motiondrawer-basic", title: "Sheet met veeg", description: "Sleep het paneel opzij of aan het greepje naar beneden." }],
    props: ["MotionDrawerContentProps"],
    notes: [
      "Vervangt alleen DrawerContent. Drawer, DrawerHeader, DrawerBody en DrawerFooter blijven dezelfde.",
      "Respecteert prefers-reduced-motion: dan vervaagt het paneel in plaats van te schuiven en staat slepen uit.",
    ],
  },
  {
    slug: "otp-verification",
    name: "OtpVerification",
    description: "Verificatiekaart die zichzelf controleert: rij, raster, samensmelten, bevestiging.",
    category: "Motion",
    files: ["../motion/otp-verification.tsx", "../motion/motion.css"],
    requires: ["motion"],
    demos: [
      { key: "otpverification-basic", title: "De volledige animatie", description: "Typt zichzelf in en herhaalt; typ gerust mee." },
      { key: "otpverification-verify", title: "Met echte controle", description: "onVerify beslist; een foute code schudt en wist zichzelf.", align: "block" },
      { key: "otpverification-orbit", title: "Variant orbit", description: "De cijfers draaien rond het midden terwijl je backend antwoordt, met tellertje en knop." },
    ],
    props: ["OtpVerificationProps", "OtpVerificationTexts"],
    notes: [
      "onVerify mag async zijn: de raster-animatie loopt door terwijl je backend antwoordt. false of een fout geeft de foutstatus.",
      "Zonder demoCode blijft de kaart stil staan wachten op invoer — demoCode, autoPlay en loop zijn er alleen voor voorbeelden.",
      "OtpInput is het kale invoerveld; dit is de volledige kaart met animatie eromheen.",
      "variant=\"orbit\" laat de vakjes rond het midden draaien in plaats van naar een raster te schuiven; action, icon en resendAfter voegen de knop, het icoontje en het tellertje toe.",
      "Bij \"verminderde beweging\" vervallen de veren en de snippers; de statuswissels blijven.",
    ],
  },
  {
    slug: "upload-button",
    name: "UploadButton",
    description: "Bestandsveld waarvan de knop over het veld openklapt en zich vult met de voortgang.",
    category: "Motion",
    files: ["../motion/upload-button.tsx", "../motion/motion.css"],
    requires: ["motion"],
    demos: [
      { key: "uploadbutton-basic", title: "Kiezen en uploaden" },
      { key: "uploadbutton-real", title: "Met een echte upload", description: "onUpload krijgt het bestand en een functie voor de voortgang.", align: "block" },
    ],
    props: ["UploadButtonProps", "UploadButtonTexts"],
    notes: [
      "Zonder onUpload loopt er een nep-voortgang van demoDuration ms — handig voor voorbeelden en prototypes.",
      "resetAfter={false} laat de knop op \"klaar\" staan; anders springt hij na die tijd terug naar het begin.",
    ],
  },
  {
    slug: "payment-checkout",
    name: "PaymentCheckout",
    description: "Kaartgegevens invullen met een kaart die meeschrijft, omdraait voor de CVC en de betaling afrondt.",
    category: "Motion",
    files: ["../motion/payment-checkout.tsx", "../motion/motion.css"],
    dependsOn: ["field", "input", "button"],
    requires: ["motion"],
    demos: [
      { key: "paymentcheckout-basic", title: "De volledige flow", description: "Vult zichzelf in en betaalt; de kaart blijft over tijdens het verwerken.", align: "block" },
      { key: "paymentcheckout-real", title: "Zelf invullen", description: "onPay beslist of de betaling lukt.", align: "block" },
    ],
    props: ["PaymentCheckoutProps", "PaymentValues", "PaymentCheckoutTexts"],
    notes: [
      "Het merk (visa, mastercard, amex) volgt uit de eerste cijfers; amex krijgt de 4-6-5-groepering.",
      "De kaart draait om zodra het CVC-veld focus krijgt en weer terug bij blur.",
      "Het bedrag wordt opgemaakt met Intl.NumberFormat — geef currency en locale mee voor een andere munt.",
      "De kaart gebruikt de accentkleur van je thema als verloop; één token aanpassen herkleurt ze.",
    ],
  },
  {
    slug: "send-button",
    name: "SendButton",
    description: "De knop vouwt zich tot een papieren vliegtuigje dat wegvliegt, en komt terug als \"verzonden\".",
    category: "Motion",
    files: ["../motion/send-button.tsx", "../motion/use-action.ts", "../motion/motion.css"],
    requires: ["motion"],
    demos: [{ key: "sendbutton-basic", title: "Versturen en mislukken" }],
    props: ["SendButtonProps"],
    notes: ["onSend mag async zijn; false of een fout geeft de rode staat. Met resetAfter={false} blijft het resultaat staan."],
  },
  {
    slug: "order-button",
    name: "OrderButton",
    description: "Bestelknop waar een bestelwagen doorheen rijdt voor ze op groen \"besteld\" springt.",
    category: "Motion",
    files: ["../motion/order-button.tsx", "../motion/use-action.ts", "../motion/motion.css"],
    requires: ["motion"],
    demos: [{ key: "orderbutton-basic", title: "Bestellen" }],
    props: ["OrderButtonProps"],
    notes: ["De rit duurt 1,5 seconde; een sneller antwoord van je backend wacht netjes tot de wagen buiten beeld is."],
  },
  {
    slug: "add-to-cart-button",
    name: "AddToCartButton",
    description: "Knop die samentrekt tot een mandje, het artikel erin laat vallen en de teller optelt.",
    category: "Motion",
    files: ["../motion/add-to-cart-button.tsx", "../motion/use-action.ts", "../motion/motion.css"],
    requires: ["motion"],
    demos: [{ key: "addtocart-basic", title: "Toevoegen" }],
    props: ["AddToCartButtonProps"],
    notes: ["De teller werkt controlled (count + onCountChange) of uncontrolled (defaultCount); hint={null} laat de regel eronder weg."],
  },
  {
    slug: "share-button",
    name: "ShareButton",
    description: "Deelknop die openwaaiert naar je kanalen en de link op het klembord zet.",
    category: "Motion",
    files: ["../motion/share-button.tsx", "../motion/motion.css"],
    requires: ["motion"],
    demos: [{ key: "sharebutton-basic", title: "Kanalen kiezen" }],
    props: ["ShareButtonProps", "ShareChannel"],
    notes: [
      "Een kanaal met href opent een venster ({url} wordt vervangen); zonder href wordt de link gekopieerd.",
      "Escape of een klik ernaast klapt de waaier weer dicht.",
    ],
  },
  {
    slug: "delete-button",
    name: "DeleteButton",
    description: "De vuilnisbak schuift over het label heen en eet het op, daarna volgt de bevestiging.",
    category: "Motion",
    files: ["../motion/delete-button.tsx", "../motion/use-action.ts", "../motion/motion.css"],
    requires: ["motion"],
    demos: [{ key: "deletebutton-basic", title: "Vol en zacht" }],
    props: ["DeleteButtonProps"],
    notes: ["Voor iets dat echt weg is: combineer met AlertDialog om te laten bevestigen vóór onDelete draait."],
  },
  {
    slug: "layout",
    name: "Stack, Row & Grid",
    description: "Layout-primitieven: Container, Stack, Row, Grid en Spacer op één afstandsschaal.",
    category: "Layout",
    files: ["layout.tsx", "layout.css"],
    demos: [{ key: "layout-basic", title: "De vijf samen", align: "block" }],
    props: ["ContainerProps", "StackProps", "RowProps", "GridProps", "SpacerProps"],
    notes: [
      "gap gaat van xs tot xl en gebruikt dezelfde schaal als de rest van de library, dus geen losse pixelwaarden in je markup.",
      "Grid zonder cols schikt zijn kolommen vanzelf: min bepaalt hoe smal een kolom mag worden.",
      "Met as render je een ander element, bijvoorbeeld <Stack as=\"ul\"> voor een echte lijst.",
    ],
  },
  {
    slug: "text",
    name: "Text",
    description: "Eén component voor alle tekst: variant, toon, gewicht, uitlijning en afkappen.",
    category: "Basis",
    files: ["text.tsx", "text.css"],
    demos: [{ key: "text-basic", title: "Varianten en afkappen", align: "block" }],
    props: ["TextProps"],
    notes: [
      "De variant kiest ook het element: h2 wordt een <h2>, body een <p>. Met as overschrijf je dat.",
      "truncate kapt één regel af, lines={2} kapt af na een vast aantal regels.",
    ],
  },
  {
    slug: "key-value",
    name: "KeyValueList",
    description: "Labels met hun waarde, zoals in een dossierkop of detailpaneel.",
    category: "Data",
    files: ["key-value.tsx", "key-value.css"],
    demos: [{ key: "keyvalue-basic", title: "Horizontaal en in kolommen", align: "block" }],
    props: ["KeyValueListProps", "KeyValueProps"],
    notes: [
      "Rendert een echte <dl> met <dt> en <dd>, dus schermlezers lezen label en waarde als paar.",
      "Een lege waarde wordt automatisch een streepje; met empty kies je zelf wat er staat.",
    ],
  },
  {
    slug: "filter-panel",
    name: "FilterPanel",
    description: "Filterkolom met groepen, tellers, avatars, \"toon meer\" en een wisknop.",
    category: "Navigatie",
    files: ["filter-panel.tsx", "filter-panel.css"],
    demos: [{ key: "filterpanel-basic", title: "Dossiers filteren", align: "block" }],
    props: ["FilterPanelProps", "FilterGroupProps", "FilterOptionProps"],
    notes: [
      "maxVisible zet de rest van een groep achter \"toon meer\"; collapsible maakt de hele groep inklapbaar.",
      "FilterOption werkt als checkbox of radio en kent ook de derde staat (indeterminate) voor een groep die half aan staat.",
      "tone=\"inverted\" geeft dezelfde donkere rail als de Sidebar.",
    ],
  },
  {
    slug: "tree",
    name: "Tree",
    description: "Hiërarchische boom met in- en uitklapbare takken en toetsenbordnavigatie.",
    category: "Data",
    files: ["tree.tsx", "tree.css"],
    demos: [{ key: "tree-basic", title: "Mappenboom", align: "block" }],
    props: ["TreeProps", "TreeItemProps"],
    notes: [
      "Pijltjes omhoog en omlaag lopen door de zichtbare items, rechts klapt een tak open, links weer dicht.",
      "Welke takken openstaan is controlled (expanded) of uncontrolled (defaultExpanded); hetzelfde geldt voor de selectie.",
    ],
  },
  {
    slug: "number-field",
    name: "NumberField",
    description: "Numeriek veld met stappers, grenzen, eenheid en opmaak.",
    category: "Formulieren",
    files: ["number-field.tsx", "number-field.css"],
    dependsOn: ["field"],
    demos: [{ key: "numberfield-basic", title: "Aantallen, bedragen en eenheden", align: "block" }],
    props: ["NumberFieldProps"],
    notes: [
      "Pijltjes stappen met step, PageUp en PageDown met largeStep, Home en End springen naar min en max.",
      "format gaat rechtstreeks naar Intl.NumberFormat, dus valuta en percentages komen er gratis bij.",
      "Tijdens het typen blijft je invoer staan; pas bij blur wordt ze geklemd en opgemaakt.",
    ],
  },
  {
    slug: "input-group",
    name: "InputGroup",
    description: "Plakt velden, selects, knoppen en vaste teksten aan elkaar tot één controle.",
    category: "Formulieren",
    files: ["input-group.tsx", "input-group.css"],
    dependsOn: ["input"],
    demos: [{ key: "inputgroup-basic", title: "Voorvoegsel, knop en eenheid", align: "block" }],
    props: ["InputGroupProps"],
    notes: [
      "Alleen de buitenste hoeken blijven rond; de randen ertussen vallen weg en het element met focus komt bovenop.",
      "Werkt met Input, Select, Button en InputGroupText, en met vertical ook onder elkaar.",
    ],
  },
  {
    slug: "tags-input",
    name: "TagsInput",
    description: "Getypte waarden worden verwijderbare chips, met suggesties en validatie.",
    category: "Formulieren",
    files: ["tags-input.tsx", "tags-input.css"],
    dependsOn: ["field"],
    demos: [{ key: "tagsinput-basic", title: "Labels en genodigden", align: "block" }],
    props: ["TagsInputProps"],
    notes: [
      "Enter en de scheidingstekens maken een chip; Backspace in een leeg veld haalt de laatste weer weg.",
      "Met validate keur je een waarde af, bijvoorbeeld een e-mailadres dat niet klopt.",
    ],
  },
  {
    slug: "code-block",
    name: "CodeBlock",
    description: "Code met kleuring, taallabel, regelnummers, oplichtende regels en een kopieerknop.",
    category: "Data",
    files: ["code-block.tsx", "code-block.css"],
    demos: [{ key: "codeblock-basic", title: "Code tonen", align: "block" }],
    props: ["CodeBlockProps", "CodeProps"],
    notes: [
      "De kleuring is een eigen highlighter in één doorgang — geen dependency, en genoeg voor TSX, CSS en shell.",
      "highlightLines licht regels op, lineNumbers zet er nummers bij en wrap breekt lange regels af.",
    ],
  },
  {
    slug: "navigation-menu",
    name: "NavigationMenu",
    description: "Horizontale hoofdnavigatie met dropdowns en een megamenu in kolommen.",
    category: "Navigatie",
    files: ["navigation-menu.tsx", "navigation-menu.css"],
    demos: [{ key: "navigationmenu-basic", title: "Megamenu en dropdowns", align: "block" }],
    props: ["NavigationMenuProps", "NavigationMenuItemProps", "NavigationMenuSectionProps", "NavigationMenuLinkProps"],
    notes: [
      "Panelen openen bij hover met een kleine vertraging bij het sluiten, zodat je diagonaal naar het paneel kan bewegen.",
      "Pijltjes links en rechts lopen door de triggers, Escape sluit en zet de focus terug; klikken werkt ook zonder muisbeweging.",
      "Een item zonder kinderen rendert als gewone link met href; mega zet het paneel over de volle breedte in kolommen.",
    ],
  },
  {
    slug: "autocomplete",
    name: "Autocomplete",
    description: "Tekstveld met voorstellen: vrije invoer blijft toegestaan.",
    category: "Formulieren",
    files: ["autocomplete.tsx", "autocomplete.css"],
    dependsOn: ["field"],
    demos: [{ key: "autocomplete-basic", title: "Steden zoeken", align: "block" }],
    props: ["AutocompleteProps", "AutocompleteOption"],
    notes: [
      "Anders dan Combobox mag de waarde ook iets zijn dat niet in de lijst staat; de lijst is een hulpje, geen keuzeslot.",
      "Filteren gebeurt standaard op label en beschrijving; geef filter={false} bij voorstellen die je zelf al van de server haalt.",
      "De lijst hangt in een Portal en volgt het veld met useAnchorPosition, dus ook binnen een dialog of scrollpaneel.",
    ],
  },
  {
    slug: "color-picker",
    name: "ColorPicker",
    description: "Kleurvlak met tint, doorzichtigheid, hexveld en vaste kleuren.",
    category: "Formulieren",
    files: ["color-picker.tsx", "color-picker.css"],
    demos: [{ key: "colorpicker-basic", title: "Kleur kiezen", align: "block" }],
    props: ["ColorPickerProps"],
    notes: [
      "De waarde is altijd hex: \"#rrggbb\", of \"#rrggbbaa\" zodra alpha aanstaat.",
      "Tint blijft bewaard wanneer je naar zwart of wit sleept, zodat de schuif niet terugspringt naar rood.",
      "Pijltjes verplaatsen de greep, Shift maakt grotere stappen; de pipetknop verschijnt alleen als de browser EyeDropper ondersteunt.",
    ],
  },
  {
    slug: "scrollspy",
    name: "Scrollspy",
    description: "Inhoudsopgave die meeloopt met de sectie die in beeld staat.",
    category: "Navigatie",
    files: ["scrollspy.tsx", "scrollspy.css"],
    demos: [{ key: "scrollspy-basic", title: "Op deze pagina", align: "block" }],
    props: ["ScrollspyProps", "ScrollspyItem"],
    notes: [
      "Gebruikt IntersectionObserver, geen scroll-listener, dus het kost niets tijdens het scrollen.",
      "offset houdt rekening met een vaste kopbalk; root laat je binnen een scrollend paneel werken in plaats van het venster.",
      "Klikken scrolt zacht (tenzij smooth={false}) en schrijft de hash weg met replaceState, zonder sprong in de geschiedenis.",
    ],
  },
  {
    slug: "meter",
    name: "Meter",
    description: "Meterbalk voor een meetwaarde binnen een bereik, met drempelkleuren.",
    category: "Feedback",
    files: ["meter.tsx", "meter.css"],
    demos: [{ key: "meter-basic", title: "Opslag, belasting en doelen", align: "block" }],
    props: ["MeterProps", "MeterThreshold"],
    notes: [
      "Anders dan Progress toont Meter geen vooruitgang maar een stand: opslag, belasting, voorraad.",
      "thresholds kleurt de balk vanaf een waarde, bijvoorbeeld groen tot 60, amber tot 85, daarna rood.",
      "marker zet een streepje voor een doel of grens; role=\"meter\" met aria-valuenow leest correct voor.",
    ],
  },
  {
    slug: "visually-hidden",
    name: "VisuallyHidden",
    description: "Tekst enkel voor schermlezers, plus een SkipLink naar de inhoud.",
    category: "Layout",
    files: ["visually-hidden.tsx", "visually-hidden.css"],
    demos: [{ key: "visuallyhidden-basic", title: "Verborgen tekst en sprongkoppeling", align: "block" }],
    props: ["VisuallyHiddenProps", "SkipLinkProps"],
    notes: [
      "Verbergt zonder display: none, dus schermlezers lezen de tekst wel voor.",
      "SkipLink is dezelfde techniek, maar wordt zichtbaar zodra hij focus krijgt; targetId wijst naar de inhoud.",
    ],
  },
  {
    slug: "reorder-list",
    name: "ReorderList",
    description: "Lijst waarvan je de volgorde sleept, met of zonder greepje.",
    category: "Motion",
    files: ["../motion/reorder-list.tsx", "../motion/motion.css"],
    requires: ["motion"],
    demos: [{ key: "reorder-basic", title: "Taken herschikken", description: "Sleep een rij naar boven of beneden; de rest schuift mee.", align: "block" }],
    props: ["ReorderListProps", "ReorderListItemProps"],
    notes: [
      "Elke waarde in values moet uniek zijn; motion gebruikt ze als identiteit.",
      "Met handle sleep je alleen aan het greepje, zodat knoppen in de rij klikbaar blijven.",
    ],
  },
  {
    slug: "motion-segmented",
    name: "MotionSegmented",
    description: "Segmented waarbij de actieve achtergrond meeschuift in plaats van verspringt.",
    category: "Motion",
    files: ["../motion/motion-segmented.tsx", "../motion/motion.css"],
    dependsOn: ["segmented"],
    requires: ["motion"],
    demos: [{ key: "motionsegmented-basic", title: "Meeschuivende indicator", description: "Zelfde API als Segmented." }],
    props: ["MotionSegmentedProps"],
    notes: ["Dezelfde props als Segmented; layoutId alleen nodig als er meerdere naast elkaar staan."],
  },
];

export function componentBySlug(slug: string): ComponentEntry | undefined {
  return COMPONENTS.find((component) => component.slug === slug);
}

export function componentsByCategory(): Array<{ category: string; items: ComponentEntry[] }> {
  return CATEGORIES.map((category) => ({
    category,
    items: COMPONENTS.filter((component) => component.category === category),
  })).filter((group) => group.items.length > 0);
}

export function newComponents(): ComponentEntry[] {
  return COMPONENTS.filter((component) => component.isNew);
}

export function updatedComponents(): ComponentEntry[] {
  return COMPONENTS.filter((component) => component.isUpdated && !component.isNew);
}

/** Welk label hoort bij dit item: "new", "updated" of geen. */
export function entryTag(entry: { isNew?: boolean; isUpdated?: boolean }): "new" | "updated" | null {
  if (entry.isNew) return "new";
  if (entry.isUpdated) return "updated";
  return null;
}
